### ISSUE TITLE
on iOS, URL schema doesn't work when you use a facebook social connection

### ISSUE THREAD

**Issue by ghost** [codenameone/CodenameOne#1159]
Original [issue 1160](https://code.google.com/p/codenameone/issues/detail?id=1160) created by codenameone on 2014-07-30T04:44:04.000Z:

If you use login with facebook, the URL schema doesn't work :-(
Apparently the plist file gets mixed up.

Ram

**Comment by igo211** [comment]
Did the fix ever get deployed to the build server?
The suggested build argument ( ios.urlScheme ) doesn't appear to work.

**Comment by codenameone** [comment]
Sorry, its `ios.urlSchemes` not `ios.urlScheme`.

**Comment by igo211** [comment]
Nope.
I've tried this several different ways, and it's still not working.
Perhaps I'm not understanding the build flags involved.

if my build flags are:
facebook.appId=<myFacebookAppID>
ios.urlSchemes=<myScheme>

The build succeeds, but myScheme is not inserted into the plist.


if my build flags are:
facebook.appId=<myFacebookAppID>
ios.urlSchemes=<myScheme>
ios.plistInject=<XML as described in http://www.codenameone.com/blog/intercepting-urls-on-ios-android>

The build fails with the message:
error: couldn't parse contents of <filename>: The data couldn’t be read because it isn’t in the correct format.

if my build flags are:
facebook.appId=<myFacebookAppID>
ios.plistInject=<XML as described in http://www.codenameone.com/blog/intercepting-urls-on-ios-android>

The build succeeds, but myScheme is not inserted into the plist.

if my build flags are just the ios.plistInject without the facebook.appId

The build succeeds, but of course, I don't have the facebook url scheme.

**Comment by codenameone** [comment]
It should be without the plistInject. What is the value you give to the ios.urlSchemes?

**Comment by igo211** [comment]
ios.urlSchemes=whoztop

**Comment by codenameone** [comment]
I think it needs to be in the format `ios.urlSchemes=<string>whoztop</string>`
Did you look at the generated plist file?
Did you confirm that the build argument is written correctly in the codenameone_settings.properties file?

**Comment by igo211** [comment]
Ah yes, ios.urlSchemes=<string>whoztop</string>,  works... And that is quite a bit different than either
ios.urlScheme=myURL or ios.urlSchemes=myURL
as you previously stated.

It's find it very odd that you've chosen to require the <string> & </string> delimiters, but OK... it's now working, which is helpful.  Thanks much.

I suggest 3 things:

1) that you remove the requirement for the <string> & </string> delimiters/boilerplate.
2) that you also create the equivalent for android (to prevent devs from having to write the android XML boilerplate and stuff it in a tiny texfield in the IDEs).
3) That the developer guide be updated (regardless of 1 & 2) to include the new info, so that other devs don't waste time trying to semi-randomly search for this issue entry.

**Comment by igo211** [comment]
hmmm... looks like github is stripping out the xml tags in my comments (specifically the `<string>` and `</string>`)

so, one more time.... this time with backticks...

Ah yes, ios.urlSchemes=whoztop, works... And that is quite a bit different than either
ios.urlScheme=myURL or ios.urlSchemes=myURL
as you previously stated.

It's find it very odd that you've chosen to require the `<string>` & `<string>` delimiters, but OK... it's now working, which is helpful. Thanks much.

I suggest 3 things:

1) that you remove the requirement for the `<string>` & `<string>` delimiters/boilerplate.
2) that you also create the equivalent for android (to prevent devs from having to write the android XML boilerplate and stuff it in a tiny texfield in the IDEs).
3) That the developer guide be updated (regardless of 1 & 2) to include the new info, so that other devs don't waste time trying to semi-randomly search for this issue entry.
