### ISSUE TITLE
ArrayIndexOutOfBoundsException in com.codename1.ui.Container$Anim.animate

### ISSUE THREAD

**Issue by ghost** [codenameone/CodenameOne#1190]
Original [issue 1191](https://code.google.com/p/codenameone/issues/detail?id=1191) created by codenameone on 2014-09-24T11:58:05.000Z:

I have no idea how to reproduce this.
But How can that happen anyway?

java.lang.ArrayIndexOutOfBoundsException: 2
    at com.codename1.ui.Container$Anim.animate(Container.java:2293)
    at com.codename1.ui.Form.loopAnimations(Form.java:1121)
    at com.codename1.ui.Form.repaintAnimations(Form.java:1106)
    at com.codename1.ui.Display.edtLoopImpl(Display.java:1018)
    at com.codename1.ui.Display.mainEDTLoop(Display.java:940)
    at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by saeder** [comment]
I protest against just closing issues that have not been fixed

**Comment by codenameone** [comment]
#1571 has nothing to do with this issue.

This issue was closed in March not recently. The reason it was closed is that its not fixable. The solution as I explained above is a brand new API designed for concurrent modification. 

Your point a is incorrect. You can avoid this issue by tracking all your apps animations globally and only starting an animation as a mutation to a form completes. This means globally to a specific form not to the entire app.

Point b is painful but I don't have a valid workaround for that, if you have a constructive suggestion on how to improve the current API/implementation I'm totally open to such suggestions.

**Comment by saeder** [comment]
I disagree that this is not fixable. 
One could at least make the code more defensive in a way where the animation is just cancelled where an exception occurs.
And would it really be too diffucult to remove components from an animation when they've been removed from the parent? I don't think so.

**Comment by codenameone** [comment]
As I said feel free to suggest something constructive. 
You are thinking about an animation in one specific container and not within different containers within an elaborate hierarchy which is the reality. Keep in mind that any recursive solution will be impractical since we will need to run that for every frame and doing that would kill performance. 

We don't "just reject" ideas or requests. We gave this a lot of thought and we all looked at this and couldn't come up with a fix other than writing a new API or fixing it in client code.

**Comment by codenameone** [comment]
This was just fixed by this enhancement https://github.com/codenameone/CodenameOne/pull/1615
Its effectively a complete rework of how animations work in Codename One thru a more generic framework.
