### ISSUE TITLE
RFE: Support native clipboard on iOS

### ISSUE THREAD

**Issue by t-arn** [codenameone/CodenameOne#1435]
Current libVersion: 85
Display.copyToClipboard should copy data into the native clipboard on iOS (same as on Android)
Display.getPasteDataFromClipboard should get data from the native clipboard on iOS (same as on Android).

This would enable to programmatically share data between separate apps on iOS.

**Comment by flewby** [comment]
I would add that on android, I had to cast the clipboard object (containing text) to **CharSequence**, rather than to **String**, in order to extract the contents.  (I think the actual class on android was **SpannableString**).

I didn't test on iOS  but definitely look forward to an API that works the same on both platforms :-) !
