### ISSUE TITLE
Add support for CocoaPods in iOS builds

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1518]
This is probably especially important with newer size restrictions for iOS builds but would probably improve build times/serve utilization in general. Tools such as GoogleMaps now use CocoaPods which will allow us to significantly shrink the build file for native maps.
https://guides.cocoapods.org/using/using-cocoapods.html

This can probably be implemented thru a simple build hint.

**Comment by codenameone** [comment]
@shannah can you add this to your list of tasks?

**Comment by amiga** [comment]
This would be great, I hope it works with large files like this one that I have to upload each time libGoogleAnalyticsServices.a

**Comment by shannah** [comment]
@codenameone OK.  I'll look at it this week.

**Comment by shannah** [comment]
Did some sample runs on local machine.  Looks like a very easy modification.  When using Cocoapods it generates an xcworkspace file from the xcproject, but adds its dependencies.  Just need to test xcode build with the -workspace flag instead of the -project flag.  Other than that, it's a trivial fix.  (I just need to fix up my dev environment so that xcodebuild works.... I'm currently just generating the xcode projects, then opening in xcode locally).

**Comment by codenameone** [comment]
Can you add a sample usage?
I'm trying to adapt the GoogleMaps implementation and it's not exactly intuitive.

**Comment by shannah** [comment]
https://github.com/codenameone/CodenameOne/wiki/Working-With-iOS#using-cocoapods

I have also modified the Google maps library to use cocoapods.  The cn1lib is now 21.5k

**Comment by amiga** [comment]
Wow this is great! Does this mean I can use GoogleAnalyticsServices.a (and simlilar) without needing to include in my .jar? How do I add one that "you" dont support? Or have I got the wrong end of the stick, been a while :)

**Comment by shannah** [comment]
Yes.  https://cocoapods.org/pods/GoogleAnalytics.
You'd probably also have to change some of your imports to work with Cocoapods.  (e.g. For GoogleMaps, I had to change all of my `#import "GoogleMaps.h"` to `#import "GoogleMaps/GoogleMaps.h" etc...
