### ISSUE TITLE
createTruetypeFont can't be correct

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1635]
Looking at createTrueTypeFont with an eye to reporting the created size of fonts, the usage
of static variable "fontReturnedHeight" can't possibly be right.  On the first call, the value is
zero.  Thereafter it is chained to the initial height of the previously loaded font, so the key
under which the newly loaded font is filed will depend on the order in which fonts are loaded.

**Comment by codenameone** [comment]
Its odd but its not a bug...

First time around its 0 so it will return false as there is no 0 sized font. Since that portion of the code returns the font created by "default" the size should (in theory) always be the same (before the `derive` call which is always made). So the first usage of `fontReturnedHeight` is a cache miss anyway, the second and onward usages can be a hit or miss.

**Comment by ddyer0** [comment]
Yes, but then these initial fonts are interned in the cache as size 2
fonts, whereas the are internally some other size.  I suppose no one will ever
ask for a 2 point font, but it's still not right.

I've prototyped some code that records these initial loaded fonts in a way
that they will never be found by the .derive code, and remembers the requested
size of derived fonts.  This makes it possible to reliably generate bigger
or smaller fonts given an existing font that needs to be adjusted to fit a
box.

**Comment by codenameone** [comment]
It doesn't matter as long as the size is always the same. This is only for the use case of calling create twice with the same font name. Notice that the initial default size differs based on platform which is why we did this.
