### ISSUE TITLE
Get contacts needs to work with linked accounts on iOS

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1690]
See: https://groups.google.com/d/msg/codenameone-discussions/6YjfbK1t4Qg/f9gAGN-EHQAJ

This is probably related to this:
http://stackoverflow.com/questions/11351454/dealing-with-duplicate-contacts-due-to-linked-cards-in-ios-address-book-api

**Comment by shannah** [comment]
@codenameone I thought this was going to be quick and easy, but there are trade-offs.  I can "merge" all of the linked contacts.  But then when we "edit" a contact, which one do we choose to edit.
Merging them also has the potential to give suboptimal results.  E.g. my merging strategy right now is basically, for each contact property (first name, last name, email, phone, etc...) I just iterate through the linked contacts for a given person, and return the first non-null value for that property.  But if they have some stale contacts, then a non-preferred one might be returned.

Originally I was just going to do this all in the iOS port and just hide it as an implementation detail.  Now I think it might be better to add a "getLinkedContacts" method to Contact that returns all of the contacts that are linked to a contact.  On iOS this is easy to implement because it maps directly to a function in the address book API.  On other platforms we can just return a one element set containing "this" contact - unless the platform provides similar functionality.

**Comment by codenameone** [comment]
Then lets push this to 3.5 as the code freeze is tomorrow.

**Comment by shannah** [comment]
A gist of some partial work on this.
https://gist.github.com/shannah/a8bc0c99b68d20019ab0e09d64147041

This includes some modifications to merge linked contacts into one.  It is incomplete and untested, but may be useful as reference for when I revisit the problem.
