### ISSUE TITLE
Exception in GridBagLayout needs to wrap previous exception

### ISSUE THREAD

**Issue by MiguelMunoz** [codenameone/CodenameOne#1706]
The GridBagLayout class has a getPreferredSize(Container parent) method with this block of code:

    try { 
      validate(parent, info); 
    } catch (RuntimeException e) { 
      // awt.87=PreferredLayoutSize: {0} 
      throw new IllegalArgumentException("PreferredLayoutSize: " + e.getMessage()); //$NON-NLS-1$ 
    }
This would be much more useful if the IllegalArgumentException would wrap the previous exception instead of just including the message:

    throw new IllegalArgumentException("PreferredLayoutSize: " + e.getMessage(), e);  //$NON-NLS-1$ 
The original exception was in a formatter that I wrote, but this code eats the stack trace that would have taken me to the problem. It took about two hours to track it down. If the stack trace has been preserved, it would have taken me two minutes. Any time you catch an exception and throw a new one, you should always wrap the original.

**Comment by MiguelMunoz** [comment]
Your IDE may have an inspection to catch this problem. Mine does. In IntelliJ, it's called *'throw' inside 'catch' block which ignores the caught exception*. It's a useful inspection.

**Comment by codenameone** [comment]
We need to improve our IntelliJ support. I really like it having worked with it a bit more recently but we are all really used to NetBeans so I don't see us moving soon.
The issue here is that we don't support the exception constructor that accepts a `Throwable` at this point in time. There are some historical reasons for that but its a non-trivial fix as it goes into the VM logic.

The best I can do is add a printStackTrace() right now to solve the immediate issue.

**Comment by MiguelMunoz** [comment]
Thank you. Printing the stack trace is a big improvement. My point about IntelliJ was simply that you may be able to find an inspection in your IDE that can alert you to the problem.

**Comment by codenameone** [comment]
I got your point about IntelliJ. NetBeans inspection is also pretty amazing although IntelliJ does seem to be in a league of its own. If I will personally switch to it in the future it will be because of the amazing debugging feature where it lists the values of the variables as you step thru code!
