### ISSUE TITLE
focusLost is invoked on object that calls requestFocus on iOS

### ISSUE THREAD

**Issue by gerbenk** [codenameone/CodenameOne#1714]
Try the following piece of code. When you enter "aa" in the first field and go to the next, the focus is lost and you get a popup. After the error the focus should go back to the first field but for some reason, focusLost is called again on this first field.

```java
Form f = new Form(new BoxLayout(BoxLayout.Y_AXIS));
TextField firstName = new TextField();
firstName.setHint("First Name");
        
firstName.addFocusListener(new FocusListener() {

    @Override
    public void focusGained(Component cmp) {
    }

    @Override
    public void focusLost(Component cmp) {
        TextField field = (TextField) cmp;
        if ("aa".equals(field.getText())) {
            Dialog.show("Error", "'" + field.getText() + "' is not a valid value.", "Ok", null);
            field.requestFocus();
        }
    }
});

TextField secondName = new TextField();
secondName.setHint("Second Name");

f.addComponent(firstName);
f.addComponent(secondName);

f.show();
```

**Comment by codenameone** [comment]
You should use the [Validation framework](https://www.codenameone.com/javadoc/com/codename1/ui/validation/Validator.html) rather than handcode this. Regardless, requesting focus is probably not what you really want to do as the text field is edited.

You want to use something like `field.startEditAsync()` instead of `requestFocus()`. You should also use `hasFocus()`.
