### ISSUE TITLE
setURLHierarchy doesn't work in the JavaScript port

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1786]
The right thing to do in the case of the JavaScript port would just be to place the entire hierarchy as part of the built hierarchy then when that method is invoked just show that URL. No need for the whole tar/untar stuff we have on other platforms so this should work rather smoothly...

**Comment by codenameone** [comment]
Actually I only tested it in the preview, would it work in the full server deployment? 
If so this issue should be closed.

**Comment by shannah** [comment]
This is actually a little bit tricky because all of the files are stored in our "file system storage" which can't just be loaded in an iframe like a normal page.

ServiceWorkers look promising for achieving this:
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

I can install a service worker to intercept requests for all URLs in a particular path, and return the content stored in our file system storage.  I'll need to do some experimentation to see if there are limitations.  A couple of limitations that jump out are:

1. They are only available when using https
2. They are not available on Firefox when in private browsing mode

Another possibility is to use the proxy for this.  The app could install the HTML tar file onto the proxy behind the scenes, and the proxy could serve them.  This approach would be more robust as the iframe would be serving "real" pages.  But it would only work if using the proxy.  (I.e. I could make the .war distro work out of the box, but wouldnt' work in preview, and zip distribution would require configuration).

**Comment by codenameone** [comment]
This is actually MUCH simpler. Just package the URL hierarchy in the final result as HTML instead of the "TAR" stuff. That's a hack meant for devices. Then just show the content in the HTML directory.

This should be a 5 minute fix in the build script for the javascript port
