### ISSUE TITLE
When asking a question in dr. sbaitso and pressing enter the answer doesn't arrive

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1795]
This only happens in the JavaScript port. The question appears but the answer doesn't show up. This can create a situation where we can "ask" many questions without receiving an answer until this is finally send when we press the "Ask" button.

I'm assuming that this is triggered because of the "done listener" somehow blocking the response.

This can be reproduced with the new Dr. Sbaitso demo: https://github.com/codenameone/DrSbaitso

**Comment by shannah** [comment]
This is because the javascript port uses invokeAndBlock for editing text.  This has been an annoyance for a while and is why I've stopped using invokeAndBlock to allow for synchronous network requests.

What is happening:

Inside the done listener there is an animateLayoutAndWait(400) (to display the question).  This uses invokeAndBlock under the covers.

Meanwhile the text field gains focus for the next question - which uses invokeAndBlock again.

The first invokeAndBlock will block until the second invokeAndBlock is completed.  Since the second one is the text editing action, which won't be done until it loses focus, we have the situation at hand.

Not sure if this is fixable in invokeAndBlock.

For now, I'm changing the editText() implementation to not use invokeAndBlock.

**Comment by shannah** [comment]
Fixed by changing editText to use asynchronous callbacks rather than invokeAndBlock
https://github.com/shannah/cn1-teavm-port/commit/ea13e451f44333444fe843ddc45958b982533996
