### ISSUE TITLE
Type 4 push crashes running iOS application

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1798]
This was reported here: http://stackoverflow.com/questions/37704651/codename-one-push-notification-type-4-crashes-on-ios

It looks like a regression related to work on the background notification.

**Comment by codenameone** [comment]
@shannah if this proves too much of a problem please reassign this to me

**Comment by shannah** [comment]
Actually, the problem is pretty clear here.  On this line
https://github.com/codenameone/CodenameOne/blob/master/Ports/iOSPort/nativeSources/CodenameOne_GLAppDelegate.m#L116
It thinks it's going to get a string from the "alert" key.  But the structure is:

~~~~
{
        aps =     {
            alert =         {
                body = "Test Body";
                title = "Notification Test";
            };
            sound = default;
        };
    }
~~~~

I.e. "alert" will be a Dictionary with keys "body" and "title".

This is easy to fix (just check if it's a Dictionary, and handle it differently), I'm just not sure what value the push callback is expecting to receive here  (I don't have any test apps with push to work with right now).


@codenameone  Do I concatenate "title" and "body" into a string and pass that to the push callback with type `4`.

E.g.  "Notification Test;Test Body"
?

**Comment by codenameone** [comment]
I honestly don't recall what we did there. @chen-fishbein do you recall how the events work on Android for type 4?

**Comment by shannah** [comment]
Actually, just did a test.  Android passes it straight through.  title;body.

There are other inconsistencies though.  For example, on iOS, it just passes push type as nil for every case except type 2.  Will fix that too to be consistent with Android
