### ISSUE TITLE
Replace xpermissions and most use cases of plistInject with individual fine grained hints

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1814]
cn1libs can conflict because of complex xpermissions or plistInject entries. However, if instead of adding a permission thru xpermissions it was added via a build hint like `android.permission.COARSE_LOCATION=true` this can be done without triggering a conflict.

The same is true for many iOS build server hints which should not use the plistInject logic when possible.

**Comment by shannah** [comment]
Done for android.  Added some documentation to the wiki also.
https://github.com/codenameone/CodenameOne/wiki/Advanced-Topics-Under-The-Hood#android-native-permissions

**Comment by shannah** [comment]
plistInject build hints aren't as clear cut as the android permissions ones, since there's all kinds of different keys, and some of them we probably don't want to expose.  Each one has its own expected format.... some take dictionaries with specific keys, others are plain strings, and others are booleans.  I did a grep of my projects directory for ios.plistInject to see if there are any commonly-used ones, but it didn't pull up much.

A full list of keys can be found [here](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Introduction/Introduction.html).

**Comment by codenameone** [comment]
What you did for Android is more generic than I expected (in a good way) I don't think we need that level across the board. 

I mentioned xpermissions but I also meant a lot of the use cases of xapplication etc. e.g. I recently added `android.allowBackup` which replaces an `android.xapplication_attr` hack that existed before. 

E.g. a good example would be something like `ios.urlScheme` which solved some problems we had with generic plist injection where it collided with Facebook functionality.

This issue requires some work that isn't generic of mostly mapping common use case build hints for various OS's instead of having the very generic option.

**Comment by codenameone** [comment]
I'll close this issue as "too generic". We'll file individual issues as we need them
