### ISSUE TITLE
Pie charts are aliased

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1859]
Using the pie chart it is clear that the image isn't anti-aliased 
![codenameone screenshot 24](https://cloud.githubusercontent.com/assets/2353641/17692118/ce0caf20-63a0-11e6-9307-d87df57a7416.png)

**Comment by codenameone** [comment]
Also notice that element labels end with ... despite having space. Ideally I would rather they would be cropped in this case but it's unclear where this can be configured

**Comment by shannah** [comment]
Yes.  Had to use shape clipping which isn't antialiased.  However, on device it looks smooth.
I'll experiment with some adjustments to make it smoother.  There are a few, fairly simple things I can try (e.g. making the clip radius bigger than the circle so that the outer edge is defined by the fillRadialGradient() rather than the clip shape...

**Comment by codenameone** [comment]
If it's just because of the gradients the long term solution might be to support proper gradient painters?

**Comment by shannah** [comment]
Also, note, you can change the label sizes using the setLabelsTextSize() or setLabelsTextFont() methods.  The former sets the size in pixels.  The latter gets the size from the font that is provided.

It calculates space based on those sizes.  Those labels are truncated because at their size they wouldn't have fit in the space provided.

**Comment by codenameone** [comment]
How do I disable the "ends with 3 points" behavior here?
The problem with this statement is that I'm not sure an end user has the tools to know what is the size available or how big I can set the font.

**Comment by shannah** [comment]
There is no option to disable it.  Changing the behaviour wouldn't be too hard though.  The actual code the does it is here:

https://github.com/shannah/iabstracts/commit/bd92ade25ea4c7007d9e07db204d2f8dd369be22

The current behaviour seems to make sense.  If there's not enough room, truncate and indicate that it's truncated.

Another option would be to let the user set preferred and min sizes, and let the view resize the text if it doesn't fit.  And only truncate once we reach the min size.

**Comment by codenameone** [comment]
I fixed it to take into account the 3 point setting which is a global preference
