### ISSUE TITLE
Density issue running on chrome Android

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1877]
When running the kitchen sink demo on my One Plus 1 Marshmallow device I see this:

![2016-08-31 17 51 05](https://cloud.githubusercontent.com/assets/2353641/18140314/a81e7fd6-6fbd-11e6-88dc-f949734af3aa.png)

When I open the JavaScript version from our website the density is all wrong causing a lot of artifacts. The bug is the size of the images:

![2016-08-31 17 50 53](https://cloud.githubusercontent.com/assets/2353641/18140345/cd51f602-6fbd-11e6-9a09-8730652a5a45.png)

**Comment by shannah** [comment]
This also seems to occur on my iPhone 6S.

**Comment by shannah** [comment]
It looks like you are using an old index.html template with that build (not the one produced by the build server).   When I try to build kitchen sink directly it looks fine on my iPhone.   So I looked at the index.html you are using on the site and it looks different.

https://gist.github.com/shannah/c885edd9fd6279a744d2d22f19cb433e

Probably the best the to do is just start with the current good index.html, and then make your customizations again.

If you want to go the other way there are a couple of key things that are probably the issue here:

1.  Add the meta viewport tag:

~~~~
<meta name="viewport"
      content="
        height = device-height,
        width = device-width,
        initial-scale = 1.0,
        minimum-scale = 1.0,
        maximum-scale = 1.0,
        user-scalable = no,
        target-densitydpi = device-dpi
        " />
~~~~

2. Add the following meta tag - though this is just for IE compatibility:

~~~~
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
~~~~

Notice that the new template also appends versioning query strings to javascript includes to prevent it from loading older versions of the lib if you update at the same url.   This template was last changed in May.

**Comment by codenameone** [comment]
I used the file from the github link which doesn't include the viewport entry and it didn't solve the issue. I added the meta tags and they didn't help either.

**Comment by shannah** [comment]
What github link?
This is the current template:
https://github.com/shannah/cn1-teavm-port/blob/master/src/main/webapp/index.html

It includes the viewport entry.  Has since May.

The version I posted in [here](https://gist.github.com/shannah/c885edd9fd6279a744d2d22f19cb433e)  (the working-index.html) is working perfectly on iPhone 6S  (which exhibits the problem you are showing here for your demo version).

Having trouble getting Nexus to connect to my local machine to test there right now... but expect same results as iPhone.

**Comment by codenameone** [comment]
OK, it was the gist link. Unfortunately you placed two files there and I didn't notice that for some reason you pasted the non-working version there... I copied it as is (using the raw) and assumed I took the latest.

Works now with the correct file. Thanks.

**Comment by shannah** [comment]
Oh.  Yeah.  I placed them both there to make it easy to compare and contrast in one place. Glad to hear it's working.
