### ISSUE TITLE
RFE: Duration picker/chooser

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1964]
Currently picker accepts a Time value but not a duration value which is no less important. This should be implemented in the same way on all supported platforms.

**Comment by ThomasH99** [comment]
Great, I can really use this!

**Comment by shannah** [comment]
I added a duration picker.  Currently it's light-weight on all platforms.   I'll investigate native options tomorrow.

**Comment by shannah** [comment]
Screenshots of current light-weight implementation:

### iOS

![image](https://user-images.githubusercontent.com/2677562/32053060-f53b6346-ba0e-11e7-93ef-adf130a6e321.png)
![image](https://user-images.githubusercontent.com/2677562/32053075-01c88c24-ba0f-11e7-8d68-1187971bf961.png)
![image](https://user-images.githubusercontent.com/2677562/32053082-0a586a80-ba0f-11e7-9e20-beb549bc7be0.png)

### Android

![image](https://user-images.githubusercontent.com/2677562/32053113-2b0a8272-ba0f-11e7-80bb-d63f6a44bd67.png)
![image](https://user-images.githubusercontent.com/2677562/32053129-3664da00-ba0f-11e7-9de6-3d12ed7c2cec.png)
![image](https://user-images.githubusercontent.com/2677562/32053142-41355086-ba0f-11e7-913f-cb93292952e9.png)

### Native Implementations

#### iOS

On iOS we can use UIDatePicker with datePickerMode set to countDownTimer, as described [here](https://developer.apple.com/documentation/uikit/uidatepicker).

![image](https://user-images.githubusercontent.com/2677562/32053532-7c900044-ba10-11e7-8ad3-3ff51a72807e.png)

#### Android

Android doesn't appear to have a built-in duration picker widget.  Some third-party ones exist though.

https://github.com/svenwiegand/time-duration-picker

![image](https://user-images.githubusercontent.com/2677562/32053680-e433859a-ba10-11e7-8123-5ecd7fb27b5c.png)

It is also possible to override the built-in [TimePickerDialog](https://developer.android.com/reference/android/app/TimePickerDialog.html) as shown [here](https://stackoverflow.com/a/4076124/2935174) so that the dialog title shows something more appropriate like "Duration xxx").  It would look something like this 

![image](https://user-images.githubusercontent.com/2677562/32053987-c4851154-ba11-11e7-847d-ea6a7cb1c3cf.png)

But without the AM/PM selector, and the title saying "Set Time" would reflect the selected duration.

A limitation of that approach is that it is limited to 24 hours duration since it is an appropriated time selector.  However, the currently light-weight implementation also has this limitation since it was built using the TimeSpinner.

#### UWP

We can use the [TimePicker](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.TimePicker) class in 24-hour mode so there is no AM/PM selector.

![image](https://user-images.githubusercontent.com/2677562/32054274-c1d0fa9e-ba12-11e7-8d57-ee8253a4b321.png)

#### Javascript

We can use the [time](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time) input.

**Comment by codenameone** [comment]
The heavyweight nature of this component has been a huge pain over the past few years. I don't think we have much of a choice on iOS but for Android I'd prefer creating a good looking cross platform picker similar to the one you showed for Android in the screenshots. It doesn't look very hard to replicate. This is something we can totally do for the next release though.

**Comment by shannah** [comment]
OK.  I've added native support for iOS.  This is only used for type PICKER_TYPE_DURATION.  Not PICKER_TYPE_DURATION_HOURS or PICKER_TYPE_DURATION_MINUTES as the iOS native control doesn't have an equivalent.
