### ISSUE TITLE
Integrate Certificate detection into ConnectionRequest API

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2058]
The https://github.com/codenameone/SSLCertificateFingerprint/ API is a bit problematic due to two factors, a server might be switched in between connection requests and it doesn't distinguish the type of the certificate (e.g. SHA1 can be returned by default).

We need an API that more closely matches the native OS API for getting the certificates of the current connection. This should give us identifiable portable keys and the type of certificate that's in use to block the certificate pinning attacks. 

I'm thinking something in the line of:

````java
public SSLCertificate[] getSSLCertificates()

public final class SSLCertifiace {
    private String certificateUniqueKey;
    private String certificateAlgorithm;

   public String getCertificteUniqueKey() {
       return certificateUniqueKey;
   }

   public String getCertificteAlgorithm() {
       return certificateAlgorithm;
   }
}
````

**Comment by shannah** [comment]
If the use-case is for Certificate pinning, then getting the SSL certificates of the current connection would need to occur before any data was sent on the connection - i.e. before the connection takes place.

Is the purpose here to support certificate pinning, or is providing "after-the-fact" inspection of certificates sufficient for this feature request?

If we want to do certificate pinning, I think we would need an API that allowed the user to add a callback to the connection request that would be called at the appropriate time in the connection request, and would give the option to cancel the request.

(Note:  I've just started looking into this problem and wrapping my head around this issue, so it is possible that I'm missing some important aspect here).

**Comment by codenameone** [comment]
This can probably use the headers callback we already have.

**Comment by shannah** [comment]
I think that happens too late.  That callback happens when receiving the response.  The SSL handshake (I think ... need to test) happens after connect(), but before openOutputStream() or openInputStream(). 

I.e. I think the "callback" would have to happen here:
https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/io/ConnectionRequest.java#L566

~~~~
if(timeout > 0) {
                connection = impl.connect(actualUrl, isReadRequest(), isPost() || isWriteRequest(), timeout);
            } else {
                connection = impl.connect(actualUrl, isReadRequest(), isPost() || isWriteRequest());
            }

//------> RIGHT HERE

            if(shouldStop()) {
                return;
            }
~~~~

**Comment by codenameone** [comment]
OK, it's your call

**Comment by shannah** [comment]
Note:  For UWP support we'll need to change from HttpWebRequest to HttpClient.

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/90780681-5801-415c-8a9e-2b8c91b1a106/uwp-ssl-pinning?forum=wpdevelop

That sucks.  I remember trying to change it over before and ran into some problems so changed back... can't remember what the problems were.

**Comment by codenameone** [comment]
Don't go into that now. We can keep that feature as optional and not have it on UWP at this time.

**Comment by shannah** [comment]
iOS poses some challenges here as well.  We currently use NSURLConnection which uses a TLS session cache.  A challenge if only raised the first time a connection is attempted to a host.  Subsequent requests won't fire the challenge.

Reference https://developer.apple.com/library/content/qa/qa1727/_index.html

There are two solutions that I can see to this problem:

1. Keep a static cache of SSL certificates so that we capture them whenever there is a challenge, and just return the cached copy if there is no challenge.
2. Switch to NSURLSession (instead of NSURLConnection)  - and probably still keep a static cache.

The first option is fragile around some edge cases (e.g. if native code or a webview makes a request to a host before ConnectionRequest does, then the TLS cache will capture the credentials during that native request, and no challenge will ever be issued within the confines of a ConnectionRequest connection.

The second option would look largely like the first option, except that NSURLSession gives more control over clearing the TLS cache. etc, so we'd be able to deal with those fragile edge cases if necessary.  It might be a lot of work to make that change though, and would probably introduce regressions.

I'm leaning towards option 1, barring the discovery of a way to get the SSL certificate from a NSURLConnection.  The only "scary" thing about option 1 is that this is a "security" feature, so mistakes have consequences; and if we're in charge of comparing requests to our SSLCertificate cache ourselves, we might make a mistake and return the wrong certificate if we're not careful (and even if we are careful).

**Comment by codenameone** [comment]
This uses a standard `NSURLConnection` https://github.com/codenameone/SSLCertificateFingerprint/blob/master/native/ios/com_codename1_security_certfingerprint_impl_CheckCertInternalImpl.m

So I'm guessing that's good enough. The use case is that the attack happens if the server is replaced after the first connection is made so a new challenge will happen. Option 1 should work just fine, there is an assumption in this defence that the app wasn't compromised.

**Comment by shannah** [comment]
Yes.  That has the same problem.  I was using that as a reference.

I'll do option 1.  I'll do my best not to screw up the cache matching.

**Comment by shannah** [comment]
Complete for iOS, Android, and JavaSE.  I don't think it's possible on Javascript.  See note https://github.com/codenameone/CodenameOne/issues/2058#issuecomment-287435720 for description of UWP status.  (UWP will be implemented later).

Closing this issue now.
