### ISSUE TITLE
Memory leak on Native Maps

### ISSUE THREAD

**Issue by carlosverdier** [codenameone/CodenameOne#2128]
I get a crash consistently after opening and closing a form containing a native map several times. It happens on a iPad and a Android phone too. The last one is a powerful device, so it takes 28 times to crash with a OOM, always 28.

If I reuse the Form and the MapContainer instead of creating new instances each time, then it works fine.

Here is a simple test case that reproduces the problem (the finalize methods are includes to show that the forms are properly collected by the GC):

~~~~
public void start() {
        if(current != null){
            current.show();
            return;
        }
        mainForm();
    }
    private void mainForm() {
        Form hi = new Form("Map Test", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE)) {            
            protected void finalize() throws Throwable {                
                Log.p("Finaliza Form 1");
            }
        };
        Button btn = new Button("Show Map");
        hi.add(BorderLayout.CENTER, btn);        
        hi.show();
        btn.addActionListener((evt) -> {
            showMap();
        });    

    }
    private void showMap() {        
        Form hi2 = new Form("Map show", new BorderLayout()) {
            protected void finalize() throws Throwable {                      
                Log.p("Finaliza Form 2");
            }
        };
        hi2.setTransitionOutAnimator(CommonTransitions.createSlide(CommonTransitions.SLIDE_HORIZONTAL, true, 250));
        MapContainer map = new MapContainer(MAP_KEY);
        hi2.add(BorderLayout.CENTER, map);
        hi2.show();        
        Command back = new Command("Back") {
            @Override
            public void actionPerformed(ActionEvent evt) {
                hi2.removeComponent(map);
                mainForm();
            }            
        };                
        hi2.getToolbar().addCommandToLeftBar(back);
        hi2.setBackCommand(back);
        
    }
~~~~

**Comment by shannah** [comment]
I conducted the following testy:

1. Set up test project with provided sample code. 
2. Navigated back and forth between two forms.

In Simulator, Android, and iOS, the finalizer methods ran correctly showing.  I.e. there doesn't appear to be a memory leak any more.  There haven't been any changes to iOS that I'm aware of that would fix this issue, so I suspect that iOS's "delayed" garbage collection gave the mistaken impression that the finalizers weren't running (so it wasn't actually ever an issue).  On android this issue was likely fixed by https://github.com/codenameone/CodenameOne/commit/ddc2356ee77eefb64425bcdd0d8ed5aab30505bf
