### ISSUE TITLE
appHomePath is not interoperable with native code on iOS

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#2144]
`FileSystemStorage.getInstance().getAppHomePath()`
Returns a path missing a / in order to make the path absolute. 

e.g., The path starts with `file://var...` instead of `file:///var...`

It seems to work fine within Codenameone code however when passed through to be used in native code the path is invalid.

When passing through to the native code I need to do something like this first:

`String home = FileSystemStorage.getInstance().getAppHomePath();
if (home.indexOf("file://") == 0 && home.indexOf("file:///") == -1) {
       home = StringUtil.replaceAll(home, "file://", "file:///");
}`

On Android I'm not seeing this problem and passing the paths straight through to native code seems to work fine.

**Comment by codenameone** [comment]
I'm a bit concerned about fixing issues like this as people might rely on the behavior and might fail once we change this and only on the device.

There was another issue that I closed mostly because it got garbled with the Google Code migration so I have no idea who filed it: https://github.com/codenameone/CodenameOne/issues/1360

We need to verify that `file:////` works fine. If it does (which I assume so) then it shouldn't be a problem to fix it as the most common bug of using the workaround above won't cause a failure.
