### ISSUE TITLE
GuiBuilder 3.7.2 Tabs Component

### ISSUE THREAD

**Issue by AgileTechSupport** [codenameone/CodenameOne#2159]
Can create a "Tabs" component and add labels, add icons but cannot go any further. Using NetBeans 8.0.2 with CodeNameOne pluggin 3.7.2; Working with the default "GuiComponent" object and the "Chrome" theme;

1. The navigator pane doesn't show any sub-components with the Tabs
2. Adding containers and components to individual Tabs is not reflected in the GUI designer (only the tabs show up);
3. The GUI designer itself will sometimes crash or go blank when working with Tabs;

**Comment by shannah** [comment]
The changes required to make Tabs work correctly in non-autolayout mode brings a high likelihood of regressions.  I've been digging into this for the past couple of days, but I'm probably just going to shelve my work so far as its too close to the 3.8 release.

My preference would be to disable Tabs altogether in the GUI builder (i.e. just remove it from the palette as it is currently in autolayout mode), and then focus on adding good support for Tabs in autolayout mode only.

**Comment by AgileTechSupport** [comment]
Sounds reasonable. Auto-layout mode would be sufficient for me.

**Comment by LuccaPrado** [comment]
Hey @shannah  and @shai-almog, something was changed about this one? 
I was playing around with tabs component on Gui Builder, but, there's a lot that can be only done looking to the .gui file. Example:
You can add components for tab 1, but, they will not show in component explorer and you cannot add components to tab 2 trough gui builder. (Or is a skill issue on my end LOL)

**Comment by shai-almog** [comment]
Since this issue is 8 years old I have no idea. We didn't update the GUI builder in quite some time. We plan to do a major overhaul there but haven't gotten around to it yet. If you're using it and have issues/suggestions I suggest opening new issues/discussions. Ideally, include screenshots so we can make sure we're discussing the same issue.

The GUI builder needs a major overhaul especially when it comes to theming. It was designed when CSS wasn't the default and localization was still the the res file. I think we can improve it considerably.
