### ISSUE TITLE
Incomplete Javadoc of "Thread.java"

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2184]
Hello,
there is something that is missing in the Javadoc of:
CodenameOne/vm/JavaAPI/src/java/lang/Thread.java

Look at the last sentence of the class Javadoc:
«For example, a thread that computes primes larger than a stated value could be written as follows:»

The remaining text is missing.

**Comment by codenameone** [comment]
These are Java classes. We generated them automatically using a tool called codavaj which takes JavaDoc and converts it to Java stubs (get it, javadoc in reverse = codavaj). 

Anyway, it has its issues but since it only applies to classes that are already a part of JavaSE this is probably not a big deal. I'll just remove the second paragraph as the JavaDoc proper can cover that.
