### ISSUE TITLE
Rich Push Notification

### ISSUE THREAD

**Issue by diamondobama** [codenameone/CodenameOne#2208]
Codename One should support high-level customization of push notification on iOS and Android. Currently, the only push that could be sent is basic.

Some of the features that can be added are:

- Adding custom action buttons to notifications other than the default **Open** button, e.g. **Reply** and **Save for Later** buttons.
- Writing and posting text from within notification, like iMessage Reply.
- Adding an image to a notification.
- Showing a different text when a notification is expanded.
-  Adding a frame to push content.

Examples of some of these features can be found below:

![asset 1](https://user-images.githubusercontent.com/7268931/30063248-53782432-924e-11e7-80da-1bb091c39913.PNG)
![asset 2](https://user-images.githubusercontent.com/7268931/30063246-537774ce-924e-11e7-9da3-1446e80a71d1.JPG)
![asset 3](https://user-images.githubusercontent.com/7268931/30063247-537796de-924e-11e7-8ac6-01d330fdb3c4.PNG)
![asset 4](https://user-images.githubusercontent.com/7268931/30063249-537b691c-924e-11e7-999b-1a11b0dcfc73.JPG)
![asset 5](https://user-images.githubusercontent.com/7268931/30063250-537d745a-924e-11e7-800f-503fe7a819cf.JPG)
![asset 6](https://user-images.githubusercontent.com/7268931/30063252-545673d6-924e-11e7-9170-026d9392364b.JPG)

**Comment by codenameone** [comment]
I'd like to address these but all of my issues are going to 5.0 right now so I'm pushing back all RFE's.

**Comment by shannah** [comment]
Custom actions and image attachments have been added.   See 
https://github.com/codenameone/CodenameOne/wiki/Push-Notifications

I have not added:

1. support for text input inside push notifications (e.g. reply) - This can be implemented on iOS and Android fairly easily... and I still plan to do this.
2. Different text when expanded.  -  This is trickier, as the examples that you posted are implemented using a custom UIView from the app extension - and there are major limitations on what you can do in this context - e.g. we can't just show a Codename One view.  I have a few ideas on how we can achieve something in this space, but I'll need to experiment.

I don't know what "Adding a frame to push content." is referring to.


NOTE: Image attachment support requires an additional provisioning profile to be generated.  The certificate wizard will generate this automatically and make it available to the build server during builds - but you'll need to generate new provisioning profiles for your app (using the certificate wizard) to trigger this.

**Comment by shannah** [comment]
Status update:  Test input is implemented in iOS, but not in Android yet.  I have run into some difficulty getting android to work properly.  Will take another shot at it soon.

I don't think I'm going to include the "Different text when expanded" in this RFE.  It may be best handled natively.

**Comment by shannah** [comment]
I have finally added support for text replies as part of a push notification on Android.   This completes this issue. 

Example usage.  

The app main class should implement PushActionProvider.  It will define a method that returns a set of categories.  E.g.

~~~~
@Override
    public PushActionCategory[] getPushActionCategories() {
        return new PushActionCategory[]{
            new PushActionCategory("fo", new PushAction[]{
                new PushAction("yes", "Yes"),
                new PushAction("no", "No"),
                new PushAction("maybe", "Maybe", null, "Enter reason", "Reply")
            })
            
        };
    }
~~~~

Then, when sending a push notification, you can specify the "category" of the message.  If the category corresponds with a defined category in your getPushActionCategories() method, then the user will be presented with a set of buttons corresponding to the PushActions in that category.  

In the above example, we would send a push type 99 and a body of 

~~~~
<push type="0" body="Hello" category="fo"/>
~~~~

This would trigger the "fo" category that we defined, which has 3 actions: Yes, No, and Maybe.  And the "Maybe" action will provide a text input because of the extra parameters provided:

~~~~
new PushAction("maybe", "Maybe", null, "Enter reason", "Reply")
~~~~

The last 2 parameters are the "hint" text and the reply button label.   On android, the notification will look like

![image](https://user-images.githubusercontent.com/2677562/52081069-27fbc900-254e-11e9-9220-51966d911b56.png)

If you click on "Maybe" (with API 27 or higher), then you'll get a text field to enter a reply directly.

You can retrieve both which action was pressed, and what the user text input was using the PushContent class.

An example push callback method to retrieve this data:

~~~~
@Override
    public void push(String value) {
        PushContent data = PushContent.get();
        if (data != null) {
            System.out.println("Image URL: "+data.getImageUrl());
            System.out.println("Category: "+data.getCategory());
            System.out.println("Action: "+data.getActionId());
            System.out.println("Text Response: "+data.getTextResponse());
        } else {
            System.out.println("PushContent is null");
        }
        System.out.println("Push "+value);
        Display.getInstance().callSerially(()->{
            Dialog.show("Push received", value, "OK", null);
        });
    }
~~~~
