### ISSUE TITLE
Sudden Crash on iOS when manipulating images from the camera.

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#2285]
I've had this problem for a long time now but it has got significantly worse in the past week or two (since 3.8 came out I think).

The attached code takes a photo from the camera creates 10 buttons using a scaled copy of the image and  adds them to the layout.

On Android you can repeat this seemingly forever we got to over 1000 buttons added without any issue at all. On iOS after 100 buttons added it will crash back to the device home screen and disconnect from xcode without any memory errors or stacktrace or even a native crash report.

Without the loop - only adding one button per photo - you can take 100 photos but it will still crash. If the loop adds 10 buttons as it does now you can take around 10 photos, if the loop is run 50 times per photo you can take 1 or 2 before it crashes. Only calling capture and not adding any images to buttons or the layout can be done indefinitely as long as the path returned is never used.

Wrapping the image manipulations in callSerially makes no difference. 

[CaptureTest.java.zip](https://github.com/codenameone/CodenameOne/files/1504264/CaptureTest.java.zip)

**Comment by shannah** [comment]
I'm looking into this now.    Here is your code.  Please just insert code directly in the post in future as it's difficult when it is zipped up.

~~~~
private final List<Button> buttons = new ArrayList<>();
    public void testIOSCapturePhotoMemoryLeak() {
        Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER));

        Button getStarted = new Button("Take a photo");
        FontImage.setMaterialIcon(getStarted, FontImage.MATERIAL_CAMERA);
        getStarted.setUIID("GetStarted");
        hi.addComponent(BorderLayout.SOUTH, getStarted);
        Container c = new Container();
        c.setScrollableY(true);

        hi.add(BorderLayout.CENTER, c);
        int size = convertToPixels(10);
        getStarted.addActionListener((e) -> {
            //for (Button b : buttons) {
            //    b.getIcon().dispose();
            //    b.remove();
            // }
            // buttons.clear();

            String path = Capture.capturePhoto(640, -1);
            //   callSerially(() -> {
            try {
                for (int i = 0; i < 10; i++) {
                    Image img = Image.createImage(path);
                    float ratio = ((float) size) / ((float) img.getHeight());
                    Image imageScaled = img.scaled(size, size);
                    Button b = new Button(imageScaled);
                    b.putClientProperty("originalPath", path);
                    buttons.add(b);
                    c.add(b);
                    c.revalidate();
                    // imageScaled.dispose();
                    img.dispose();
                }
            } catch (IOException ex) {
                Log.e(ex);
            }

            // });
        });

        hi.show();
    }
~~~~

The main problem here is that you are creating lots of images, and none of them can ever be gc'd because they are included in the UI as button icons.  Implementation differences between Android and iOS will cause iOS to run out of memory sooner than Android in this example - but Android will eventually run out too.  The specific difference is that on iOS, the `Image.scaled(int,int)` method returns an image that references the same native image as the original, whereas on Android it actually generates a new bitmap.  The causes each image to take up a little bit more memory on iOS in this case.  But the important thing here is that they will both run out of memory eventually with the code snippet you provided.

**Solution**

Use EncodedImage instead of Image.  This will allow the garbage collector to free the memory associated with images that aren't currently being displayed on the screen.

E.g.  I changed your example as follows, and it appears to work indefinitely.  (Notice the 50 loop iteration - and so far I've been able to capture 20 photos on an iPhone 8 and the app hasn't crashed - and memory is stable ... it grows until GC and then returns to normal).

~~~~
private final List<Button> buttons = new ArrayList<>();
    public void testIOSCapturePhotoMemoryLeak() {
        Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER));

        Button getStarted = new Button("Take a photo");
        FontImage.setMaterialIcon(getStarted, FontImage.MATERIAL_CAMERA);
        getStarted.setUIID("GetStarted");
        hi.addComponent(BorderLayout.SOUTH, getStarted);
        Container c = new Container();
        c.setScrollableY(true);

        hi.add(BorderLayout.CENTER, c);
        int size = convertToPixels(10);
        getStarted.addActionListener((e) -> {
            //for (Button b : buttons) {
            //    b.getIcon().dispose();
            //    b.remove();
            // }
            // buttons.clear();

            String path = Capture.capturePhoto(640, -1);
            //   callSerially(() -> {
            try {
                for (int i = 0; i < 50; i++) {
                    Image img = Image.createImage(path);
                    EncodedImage encImg = EncodedImage.createFromImage(img, true);
                    float ratio = ((float) size) / ((float) img.getHeight());
                    Image imageScaled = encImg.scaledEncoded(size, size);
                    Button b = new Button(imageScaled);
                    b.putClientProperty("originalPath", path);
                    buttons.add(b);
                    c.add(b);
                    c.revalidate();
                    // imageScaled.dispose();
                    img.dispose();
                }
            } catch (IOException ex) {
                Log.e(ex);
            }

            // });
        });

        hi.show();
    }
~~~~

**Comment by codenameone** [comment]
`Image imageScaled = Image.createImage(size, size);` 
creates an image whose size in RAM is `size * size * 4 + some_os_overhead`. 

The problem is that the iOS and Android implementations are radically different so it's really a matter of what you are holding in RAM. Try ignoring the capture. Just creating blank images in Android and iOS. You should be able to create a lot of those in both.

The capture image is huge, in Android when you scale down it's discarded but in iOS it isn't. Each approach has a performance tradeoff and I'm guessing that somewhere along the line you still have a retention of the original image. Notice `dispose()` won't do anything in iOS if there is still a reference to the original image. So if you did `img.scaled(w, h);` you might still carry that overhead somewhere. The flip side of this is that `scaled` is practically instant on iOS and slow on Android.

**Comment by shannah** [comment]
I have made a small change that might fix the out of memory after  many captures.  https://github.com/codenameone/CodenameOne/commit/303fca28079864f1ac3b513cae27fe49ddfc3de6

It will be included Friday.

**Comment by DigNZ** [comment]
Thanks, this change may help. What I've found in my full app on iOS:
1. The original code using Image.scaled crashed after around 10 photos
2. Changing to EncodedImage as suggested by Steve increased this to around 50 photos
3. Changing to blank images as suggested by Shai allowed for around 100 photos.
4. Bundling a 2000x2000 pixel jpg with the app, and using that path for each 'capture' instead of Capture.capturePhoto (i.e., not opening the camera at all) allows for around 250 images to be loaded and resized before the app crashed.

I also modified Steve's approach to only use EncodedImage by opening an input stream to the image file and creating and EncodedImage from there and then scaling it. It seems to work fine but doesn't make a big difference to the limits that can be used.

Around 250 images would be completely acceptable if they were coming from the camera so if this fix helps with that issue then we can manage the scaling issue within the limits we've found.
I'll try this fix out on the weekend.
