### ISSUE TITLE
Add a warning when the user is using a reserved prefix in a file name

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2298]
Please read this discussion: [https://stackoverflow.com/questions/48076190/codename-one-play-a-sound/48107653?noredirect=1#comment83226222_48107653](https://stackoverflow.com/questions/48076190/codename-one-play-a-sound/48107653?noredirect=1#comment83226222_48107653)

My suggest is to add a warning in the log of the Simulator when the user is using a reserved prefix in a file name to prevent issues like the one in the linked discussion.

**Comment by codenameone** [comment]
A warning is problematic for this case as this might be intentional since these keywords are there for a reason. The way I see it there are two possible solutions:

- Place the file both in raw and assets making this effectively "seamless"

- Throw an exception on a call to getResourceAsStream() that includes a reserved file name

The latter option would also require documentation on this subject.
