### ISSUE TITLE
overlapping texts in TimeChart

### ISSUE THREAD

**Issue by shyamsth** [codenameone/CodenameOne#2311]
I am generating TimeChart  with attached codes and following codes and there is overlapping texts
![Uploading bar chart10.PNG…]()
 as shown attached image , how can the overlapping be solved ?
ArrayList<Date> dates = new ArrayList<Date>();
dates.add(Jun 5, 2017 12:00:00 AM);
dates.add(Jun 6, 2017 12:00:00 AM);
dates.add(Jun 7, 2017 12:00:00 AM);
dates.add(Jun 12, 2017 12:00:00 AM);

ArrayList<Date> values = new ArrayList<Date>();
values.add(2.0);
values.add(2.0);
values.add(1.0);
values.add(1.0);

Date startDate = Jun 5, 2017 12:00:00 AM;
Date endDate = Jun 12, 2017 12:00:00 AM;

DataDateValue dataDateValue = new (dates,values,startDate,endDate);

  form.add(new TimeChartGenerator().getTimeChart(dataDateValue));

[DataDateValue.zip](https://github.com/codenameone/CodenameOne/files/1633720/DataDateValue.zip)
![bar chart10](https://user-images.githubusercontent.com/8625198/34973117-fdb3d9f6-faad-11e7-822b-f79b8413e2cd.PNG)

**Comment by shannah** [comment]
Likely the code that is actually rendering the chart is inside your TimeChartGenerator class, and you don't include the source here.  There are two parameters that you can set in the renderer that will help you here.

1. `setXLabels(int)`  - set the number of labels you want on the X-Axis so that they will fit.
2. `setXAxisMin(double)` and `setXAxisMax(double)` - sets the min and max values on the x axis.  Set this to an appropriate range given your data so you don't show all kinds of irrelevant date ranges.

See https://github.com/codenameone/Charts/blob/master/src/com/codename1/demos/charts/SalesGrowthChart.java#L100 for a sample of a time chart.  The `setChartSettings()` call is where those two parameters are set.
