### ISSUE TITLE
XCode 9.2 build Splash Screen is positioned incorrectly

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2325]
This is visible in the native iphone 6 simulator

**Comment by shannah** [comment]
Changed so that 9.2 uses image splash screens by default.  Launch storyboard can be enabled using `ios.multitasking=true`.  

Moving to 5.0 milestone since 9.2 builds are "unblocked" by this feature.

**Comment by shannah** [comment]
Changed so that it doesn't use the splash screen on the LaunchScreen storyboard as there was no way to make this seamless.

Instead the LaunchScreen storyboard consists of 2 images:  Launch.Foreground.png and Launch.Background.png.  The fg image is centered in the screen, and the background is set to aspect fill in the background.  The default fg image is the app icon.  Default bg is just plain white.  You can override either of these images by including them in the native/ios directory.

You can also override the launchscreen storyboard by adding your own named LaunchScreen.storyboard in the native/ios directory.
