### ISSUE TITLE
RFE: two more options for a "Round Rect" Border

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2350]
At the moment, in the Codename One Designer, in a Style it's possible to create a Border "Round Rect" with the options "Standard", "Top only", "Bottom only". It could be nice to have also the option "Top-left and Bottom-right only" and "Top-Right and Bottom-Left only".

Thank you

**Comment by codenameone** [comment]
Can you point out a use case for that?

I can think of a use case for "Left-Only" and "Right Only" with a label that has an effect of peeking out from the side of the screen. 

I can think of a use case for everything other than one corner which can be used to "point" at an element but I can't think of a case where I'd only want one corner to be rounded.

Either way I think it's valid to say there are more use cases than originally envisioned so we should probably have 4 checkboxes that provide an "ignore" option to a specific corner leaving it effectively at a 90 degree angle.

**Comment by jsfan3** [comment]
I'm sorry for the late response.
My use case is to create buttons like the ones in the following image.

![corners](https://user-images.githubusercontent.com/1997316/37235554-d207cba2-23ff-11e8-8e67-0c58bf91e4d8.png)

**Comment by codenameone** [comment]
Thanks. I'll try to do that for 5.0 but it would need some work on the designer tool.

**Comment by codenameone** [comment]
I'll move the second portion of this issue (the designer changes) to 6.0. I think we need to re-evaluate designer changes with changing focus on CSS and the GUI builder.

**Comment by jsfan3** [comment]
I agree that the CSS support is a great innovation for Codename One: starting from its recent ufficial integration in Codename One, I stopped at all to use the Codename One Designer with new apps. I feel that working with CSS is easier, better and faster.

**Comment by codenameone** [comment]
@shannah can we add this to CSS? 
Is this reasonable for 6.0? If not push it to 7.0.

**Comment by shannah** [comment]
This is done.  Now RoundRectBorder will be used for borders where one or more corners have a radius (and all other conditions can be met by the RoundRectBorder).  E.g.  You can now do:

~~~~
RoundRectTest {
    background-color: red;
    border-radius: 2mm;
    border-top-right-radius: 0;
    border-bottom-left-radius:0;
}
~~~~

![image](https://user-images.githubusercontent.com/2677562/52588989-a0864380-2df2-11e9-8fa4-d3d747ef130d.png)

Previously this would have used a 9-piece border because it couldn't be achieved with RoundRectBorder in regular, top-only, or bottom-only mode.  Now it will use RoundRectBorder.

There are still circumstances that would cause it to use a 9-piece border.  For example, if two corners have different non-zero radii.  E.g.

~~~~
RoundRectTest {
    background-color: red;
    border-radius: 2mm;
    border-top-right-radius: 0;
    border-bottom-left-radius:3mm;
}
~~~~

This would use a 9-pice border because the bottom-left radius is 3mm, and the bottom-right radius is 2mm.
