### ISSUE TITLE
Long Strings of Emoji Break with text span in text area

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#2379]
Long emoji strings in text area break when they reach the line end. In some cases only one line is shown and in my case nothing was shown.

I'm assuming this is because text area splits up character pairs when it loops over the characters to build the newline. I'm guessing we need a special case for unicode base pairs.

````java
        String emoji = new String(new byte[]{(byte)0xf0,(byte)0x9f,(byte)0x91,(byte)0x8d,(byte)0xf0,(byte)0x9f, (byte)0x8f,(byte)0xbc,(byte)0xf0,(byte)0x9f,(byte)0x98,(byte)0x9c,(byte)0xf0,(byte)0x9f,(byte)0xa4,(byte)0x94,(byte)0xf0,(byte)0x9f,(byte)0x98,(byte)0x80,(byte)0xf0,(byte)0x9f,(byte)0x98,(byte)0x9d,(byte)0xf0,(byte)0x9f,(byte)0x99,(byte)0x84});
        String s = "";
        for(int i = 0 ; i < 30 ; i++) {
            s += emoji;
        }
        hi.add(new SpanLabel(s));
````

**Comment by tikiwade** [comment]
This is happening to me to.

**Comment by shannah** [comment]
Note.   The TextArea wrapping runs *very* slowly when the text contains a lot of characters that the Font doesn't support.  E.g. the sample:

~~~~
String emoji = new String(new byte[]{(byte)0xf0,(byte)0x9f,(byte)0x91,(byte)0x8d,(byte)0xf0,(byte)0x9f, (byte)0x8f,(byte)0xbc,(byte)0xf0,(byte)0x9f,(byte)0x98,(byte)0x9c,(byte)0xf0,(byte)0x9f,(byte)0xa4,(byte)0x94,(byte)0xf0,(byte)0x9f,(byte)0x98,(byte)0x80,(byte)0xf0,(byte)0x9f,(byte)0x98,(byte)0x9d,(byte)0xf0,(byte)0x9f,(byte)0x99,(byte)0x84});
        String s = "";
        for(int i = 0 ; i < 30 ; i++) {
            s += emoji;
        }
        hi.add(new SpanLabel(s));
~~~~

Hangs for several seconds when first loaded in simulator because the default fonts don't support emoji.  Once I downloaded an Emoji font and set that in the Style the performance improved.

That aside, this issue is now fixed.
