### ISSUE TITLE
RFE: Support selecting multiple images from gallery 

### ISSUE THREAD

**Issue by 3lix** [codenameone/CodenameOne#2383]
The current implementation for the ```Display```.```openGallery```, allows selecting one image at a time.

Today's most social apps (ex: Whatsapp, fb , etc.. )  would allow you selecting multiple images  at a time for image upload or sharing.

**Comment by 3lix** [comment]
Awesome I think this feature is well worth it. The previous flow would cause so much user pain having to select one image at a time. 

I was expecting the openGallery function to take in an int , denoting the max number of images allowed to upload. Similar feature wot WhatsApp where their max is 30 images at a time.  

Such feature could be useful whenever we would like to limit the number of images to be uploaded  for an item. For example in a buy / sell app if we allow up to 10 advertisement images for an item and the user had already uploaded two. We could pass in 8 to the openGallery, hence limiting the total of images uploaded to 10. 

I guess I didn't see the openGallery signature changing to take in the max number of images.  but  I hadn't had the chance to try it out  yet.

**Comment by shannah** [comment]
Limiting the number of selections will not be included in this feature.   This is not supported in a number of the platforms (at least JavaSE, and Javascript).  On android this would require a completely different gallery mechanism than we are using - a 3rd party library.  On iOS we already need to add a 3rd party library to support the "multiple" selection.  I'll try to choose one that supports this "limit" so that if/when we do implement a "limit", it won't require a major change.

**Comment by shannah** [comment]
Note to self:  Since iOS's UIImagePickerController doesn't support multiple image selection, I am reviewing the libraries in this list as potential replacements.  https://stackoverflow.com/a/20756957/2935174

**Comment by shannah** [comment]
All major platforms now support this.  Will be in next build server update.
