### ISSUE TITLE
Simulator (Iphone 3GS) too small on retina display

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2411]
Even though I enabled zoom, the simulator is too small on my 2560 x 1600 Retina display (MacBookPro14,1)

**Comment by amiga** [comment]
did you try double clicking the title bar, on windows 10 it makes it stretch to full screen.

**Comment by kutoman** [comment]
using the maximize window button helps, but it's still annoying.
On each simulator run I would need to do this. Furthermore it's weird that on a maximized window the "zoom" option reduces the simulator window size.

**Comment by shannah** [comment]
Use the iPhone 4 skin if you're on a Retina display.  iPhone 3GS will be small due to the lower pixel density.

**Comment by codenameone** [comment]
@shannah don't you think it makes sense that we update the default skin to iPhone 5s or maybe even iPhone X?

**Comment by kutoman** [comment]
@shannah the iphone 4 skin seems to be missing (in the skins browser)

**Comment by codenameone** [comment]
@kutoman I suggest using iPhone X or 5S or some other newer skin.

I'm reopening this so we can use this to debate the new default skin that will ship out of the box.

I think iPhone X makes a lot of sense here. We need to fix a couple of things to do that though. We need to fix the overlay when scrolling it. We also need to make "scrollable" the default because it will probably be too big for most peoples monitors.
