### ISSUE TITLE
RFE - Improvement of the UX with TextModeLayout

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2419]
At the moment, the TextModeLayout produces a very good UX when it contains only TextComponents, because in the virtual keyboard there is the option "Next" that allows to go to the next field automatically: it's very useful and intuitive.

The problem is when the TextModeLayout contains a mix of TextComponents and PickerComponents: a simple use case is the input of name (text), surname (text), birthday (picker of date), gender (picker of string), address (text), etc. In that case, the user sees the Next button only if the next field is a TextComponent, so they is forced to close the virtual keyboard, tap the next field (that will open a picker), then close the picker, tap the next field (that can be a picker or a textComponent), as so on... 

It should be more user friendly if each field _(regardless if it's a TextComponent or a PickerComponent)_ can get the focus automatically after the filling/picking of the previous field.

**Comment by codenameone** [comment]
@shannah is this doable with the lightweight/heavyweight mode?
Maybe we should expose the next text field implementation as a public API?

**Comment by shannah** [comment]
I have implemented a new focus traversal API that allows for tab/next/prev navigation between components in a form.  It works similar to the way that `tabIndex` works in HTML. 

### Tab Index

`Component` now has a `preferredTabIndex` property which specifies the tab order of a component.  There are 3 types of values that you can set here.

1. A value of `-1` means that the component is not tab-focusable (i.e. you will never get to this field by tabbing or hitting next/prev in the keyboard).  This is the default value for all components except TextArea, and Picker - which are currently the only components that are tabbable.
2. A value of `0` means that the component is tab-focusable, and the order will be dictated by the logical document order.  (The logical document order is defined in the layout managers).
3. A value greater than 0 explicitly sets the tab order.    Be careful with this as if you mix explicitly set tab orders (i.e. tabIndex > 0) with implicitly set tab orders (i.e. tabIndex == 0) in the same form, you may get unexpected results.

If you want to query the form for tab order, you can use any of the new methods on `Form`:

### Finding Next/Prev Components

1. `Form.getNextComponent(Component current)`, which gets the next component by tab order given some currently focused component.
2. `Form.getPreviousComponent(Component current)`, which gets the previous component.
3. `Form.getTabIterator(Component current)`, which gets an iterator that allows you to iterate through all of the tabbable components in the form in their tab order, starting at some currently focused component.

### Making a Component Tab-Focusable

If you are designing a new component that should be tab-focusable, you should just set the preferredTabIndex to 0.

`cmp.setPreferredTabIndex(0);`

If you want to make the component so it won't be tab-focusable, just do

`cmp.setPreferredTabIndex(-1);`

There is also a convenience method `setTraversable(boolean)` which wraps these calls to make them more intuitive.  E.g.

`cmp.setTraversable(true)` is the same as calling `cmp.setPreferredTabIndex(0)`, and `cmp.setTraversable(false)` is the same as calling `cmp.setPreferredTabIndex(-1)`.

### Default Tab Orders

It is recommended that you just stick with preferredTabIndex=0 if you want your component to be tabbable, because it's a lot of work to explicitly declare tab order for all of your fields.  Then the tab order will be automatically calculated based on the logical order of the fields on the form.  This default ordering is dictated by the layout manager.  For indexed layout managers (e.g. BoxLayout.Y, BoxLayout.X, GridLayout, FlowLayout), the tab order is simply the component order in the container.  Constraint-based layout managers like BorderLayout and TableLayout define their own orders that make logical sense.  LayeredLayout defines an order based on the x,y coordinates of its children, roughly moving top-left to bottom-right.

If you are developing your own layout manager and want a default tab order that is different than just the component order within the container, you should override the following methods:

1. `overridesTabIndices(Container)` - Return true to indicate that the layout manager provides its own traversal order.
2. `getChildrenInTraversalOrder(Container parent)` - return array of Components in the parent in the order that they should be traversed.  This returned array doesn't need to include all of the child components, only the ones that should be considered in traversal - but it may also include components that shouldn't be included in traversal, as the ineligible components will be filtered out at a later step.  In fact some of the elements of this array may be null, and those will be filtered out.

See [BorderLayout](https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/ui/layouts/BorderLayout.java#L885-L893) for an example.

See [TableLayout](https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/ui/table/TableLayout.java#L1096-L1111) for another example.

https://github.com/codenameone/CodenameOne/commit/ea79fce20ca9a328d6afc323147c6cbe717ef638
https://github.com/codenameone/CodenameOne/commit/0bc28c3f17c986c31fa521bd1d73ca494dce2156
https://github.com/codenameone/CodenameOne/commit/5e02a93c0d2cfd67956c8efaea20f2a654517ca8
https://github.com/shannah/cn1-teavm-port/commit/28b87d7ac56cd7f55719754cf3ee4a18b3fe7de4

**Comment by jsfan3** [comment]
I didn't tried it yet, however thank you very much! I think that what you wrote should be added (at least) to the developer guide.
