### ISSUE TITLE
RFE: use native password manager

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2467]
To don't lost this RFE, I copy these question & answer, taken from:
https://stackoverflow.com/questions/51112684/use-native-password-manager

**Question**
Is it possible to use (with Codename One) the native password manager to store or to get the user password?

My use case: see this screenshot of the iOS Teachable app, in the virtual keyboard there is a key icon to access the iPhone password manager (that uses the FaceID in the case of iPhone X). I know how to do a login form using a TextModeLayout, but I don’t know how to get this navite password management functionality.

**Answer**
We don't support that right now but it should be pretty easy to add based on this: https://medium.com/@abhimuralidharan/password-autofill-for-ios-apps-for-faster-login-ios-11-1d9f77deb35a

We can do that seamlessly for password fields but we'll probably need a new bit type for the username field. Ideally we should also have field types for all the properties so form auto-fill will work correctly.

We'll probably also need a build hint to set the app domain so the password manager will associate your app with the right domain. I'm not sure if we'll get to it in this release as we have a lot on our plate and summer months are rough but you can file an RFE and we'll get to it.

As a short term workaround you can use this: https://github.com/codenameone/FingerprintScanner/ to authenticate using touch ID and possibly face id (haven't tested it yet as we built this cn1lib before face id was around).

**Comment by codenameone** [comment]
I would add that I think passwords should be saved by default but we need to add an option to exclude them from this e.g.:

````java
tf.setConstrain(TextArea.PASSWORD | TextArea.BLOCK_PASSWORD_MANAGER);
````

We should also have options for the other field types like username etc. 

My one concern here is that we'll hit the 31 option limit (as we store constraints in a bitwize int. Although I think we have enough space for quite a few hints at the moment.

**Comment by shannah** [comment]
I may be doing something wrong, but I haven't been able to get the autofill working yet.   I've set up the  textContentType properties for username and password fields, but I don't see the password options on the keyboard toolbar like it shows in examples.

It could be that all of the fields have to be present (natively) in order for autofill to work.  We technically only have one field present at a time.

I may need to find a lower-level API for this functionality in order to integrate it - though that may not exist.  One idea would be to create "dummy", hidden fields of each text input type whenever any password field is activated, so that they can catch the autofill values -- then we can read them.

In any case, unless I'm doing something wrong, there will be more involved in getting this to work correctly. 

Recommend pushing to 6.0

**Comment by codenameone** [comment]
Yes. I only set it to 5.0 because I assumed it's trivial. However, thinking about it again this might not be the case since we do some manipulations on the fields.

**Comment by shannah** [comment]
I've been playing around with this a little bit more.  On iOS, our password fields already have the little "Password" button that allows the user to select a password from the password manager, although this isn't exactly autofill because the user has to use fingerprint auto to access the password list.

It is possible that if you set up the associated domains for the app (I haven't tested this out as it requires a few steps, including adding special file to the website), it will include the website credentials password as a default.  Not sure.

So far I don't see a way to do much more than this on iOS.  To properly use the iOS autofill features, all of the text fields must be present on the form at the same time, so that iOS can identify the full set (username, first name, last name, password, etc..) and autofill them.  With our current flow, we only create a single native text field at a time when it is being edited.  Changing it to keep all text fields native and active simultaneously is problematic.

I'm looking at the Android side now to see what we can do there.

**Comment by shannah** [comment]
I've been experimenting with adding a native text field control in the https://github.com/shannah/cn1-native-controls library as a means of supporting password managers better.   So far the tests are quite promising on iOS.  Using the native text field peer components results in seamless integration with the iOS password manager.  The idea would be to use these native fields only for the username and password fields in a login form.

I'm still working out some kinks with integrating it with focus traversal, etc.., but I should have something up very soon (tomorrow-ish).

**Comment by shannah** [comment]
I have implemented a native text field component class now, named NTextField that can be used for username and password fields and will work with password managers on iOS and Android.  Some sample usage:

~~~~
public void start() {
        if(current != null){
            current.show();
            return;
        }
        if (false) {
            webviewLoginTest();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        
        hi.add(new Label("Hi World"));
        Label result = new Label();
        NSelect<String> select = new NSelect<>();
        $(select).selectAllStyles()
                .setFont(Font.createTrueTypeFont(Font.NATIVE_MAIN_LIGHT, 4f))
                .setFgColor(0xff0000)
                .setBgColor(0x00ff00)
                ;
        select.setOptions("Red", "Green", "Blue", "Orange");
        select.addSelectionListener((i1, i2)->{
            result.setText(select.getOption(select.getSelectedIndex()));
            hi.revalidateWithAnimationSafety();
        });
        hi.add(result);
        
        
        
        hi.add(select);
        hi.add("Text fields");
        hi.add("Username:");
        NTextField tf1 = new NTextField(TextField.USERNAME);
        System.out.println("Setting font to main light 15mm");
        tf1.getAllStyles().setFont(Font.createTrueTypeFont(Font.NATIVE_MAIN_LIGHT, 15f));
        System.out.println("Finished setting font");
        tf1.getAllStyles().setFgColor(0x003300);
        tf1.getAllStyles().setBgTransparency(255);
        tf1.getAllStyles().setBgColor(0xcccccc);
        tf1.getAllStyles().setAlignment(CENTER);
        hi.add(tf1);
        hi.add("Password:");
        NTextField tf2 = new NTextField(TextField.PASSWORD);
        hi.add(tf2);
        hi.add("Email:");
        NTextField emailField = new NTextField(TextField.EMAILADDR);
        hi.add(emailField);
        
        tf1.addActionListener(e->{
            //tf2.setText(tf1.getText());
        });
        tf1.addChangeListener(e->{
           result.setText(tf1.getText());
           hi.revalidateWithAnimationSafety();
        });
        tf2.addActionListener(e->{
            Log.p("Action listener fired on password field");
            result.setText(tf2.getText());
            hi.revalidateWithAnimationSafety();
        });
        tf2.addDoneListener(e->{
            Log.p("Done was clicked!!!");
        });
        
        hi.add(new TextField("LW field 1"));
        hi.add(new TextField("LW field 2"));
        hi.add(new TextField("LW field 3"));
        
        Button submit = new Button("Login");
        submit.addActionListener(e->{
            Form f = new Form("Logged In", BoxLayout.y());
            Toolbar tb =new Toolbar();
            f.setToolbar(tb);
            tb.setBackCommand(new Command("") {
                @Override
                public void actionPerformed(ActionEvent e) {
                    hi.showBack();
                }
            });
            f.add("Logged In!!!");
            f.show();
        });
        hi.add(submit);
        hi.show();
    }
~~~~

One limitation is that they are opaque - you can't give them transparent backgrounds.  If the background is a solid color, you can make it look transparent by giving it the same background color as  whatever is behind it.  You can set the font, fgColor, bgColor, and alignment styles and it should work.

On platforms other than iOS and Android, it falls back to a TextField implementation.

In order for the password manager to work on iOS, you need to associate the app to your domain.  For the `ios.associatedDomains` build hint you should use the "webcredentials:" prefix rather than "applinks:"  as you do for setting up universal linking.

**Comment by jsfan3** [comment]
Thank you.

> For the ios.associatedDomains build hint you should use the "webcredentials:" prefix rather than "applinks:" as you do for setting up universal linking.

This is not clear to me: does it break the support for universal linking?

**Comment by shannah** [comment]
The ios.associatedDomains hint is comma-delimited.  You would include both the `webcredentials:example.com` and `applinks:example.com` domains if you need to support both the password manager and universal linking.

**Comment by jsfan3** [comment]
Ok, thank you!

**Comment by jsfan3** [comment]
I didn't understand if your library can be used with a `TextModeLayout`. I have a code that generate automatically a `TextModeLayout` Container with `InputComponets` binded to properties and to a Validator. I feel convenient to use `TextModeLayout` and `InputComponents` for every input like login credentials or registry data (fist name, family name, etc.). Can a `TextComponent` use your new `NTextField` instead of the standard `TextField`?

**Comment by shannah** [comment]
I haven't used TextModeLayout or InputComponent much yet.  I think you should be able to create your own InputComponent subclass that wraps a NTextField object, and just return the NTextField in the InputComponent's getEditor() method.

This is is something that could probably be added to the cn1lib, but I haven't done that.

**Comment by codenameone** [comment]
I'm not sure if it would work well with the animation. The `InputComponent` doesn't include some of the features in `TextComponent` so this would be challenging. We might be able to create an interface that goes further than the new `Editable` interface and includes all the common functionality between `TextField`/`NTextField` and then let `TextComponent` work with that interface.  We would need:

`getText()`, `setText()`, `setHint()`, `setHintIcon`, `setSingleLineTextArea`, `setColumns`, `setRows`, `setConstraint`.

Currently most of these are unavailable. Even if they were available I'm not sure if this will work nicely on the device.
