### ISSUE TITLE
Can't run an app on my iPhone 4 (iOS 9.3.5)

### ISSUE THREAD

**Issue by jsosin** [codenameone/CodenameOne#2469]
I've got this exception:

Library not loaded /System/Library/Frameworks/UserNorifications.framework/UserNotifications [...]

Reason: image not found.

**Comment by shannah** [comment]
I was unable to reproduce this.  The iPhone 4S simulator with 9.3 in Xcode 9 doesn't exhibit this problem, and you can't get an iPhone 4 simulator for Xcode 9.  My iPhone 4 test device is still on iOS 6, and you can't target iOS 6 anymore from Xcode 9 ... and I'm unable to easily update to a newer OS on that iPhone 4 because it can't log into my Apple account since I enabled 2FA.

But...  I made the UserNotifications.framework optional which will probably fix this issue.  This will be available in the next server update.
