### ISSUE TITLE
[BUG] Picker scrolls down the Form when used

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2476]
If opening a (native or lightweight) Picker on iPhone moves the Form because there isn't enought space, when it will be closed the Form will remain scrolled down. Please see this video:
https://jmp.sh/LLbEXxB

The code that I used to reproduce this bug:
```
        Form hi = new Form("Hi World", BoxLayout.y());
        Container myBox = new Container(BoxLayout.y());
        for (int i = 0; i < 15; i++) {
            myBox.add(new Label("Hi World"));
        }
        Picker myPicker = new Picker();
        myPicker.setType(Display.PICKER_TYPE_STRINGS);
        myPicker.setStrings("StringA", "StringB", "StringC");
        // myPicker.setUseLightweightPopup(true);
        myBox.add(FlowLayout.encloseCenter(myPicker));
        hi.add(myBox);
        hi.show();
```

**Comment by jsfan3** [comment]
Thank you. However I've just discovered that this issue is still present. Please see this video:
https://www.informatica-libera.net/videoLavoro/bugScrolling.mp4

**Comment by shannah** [comment]
Probably it's not deployed to the server yet

**Comment by shannah** [comment]
That a slightly different, though related, problem, that has existed in CN1 since its inception.  When the keyboard is hidden, the screen-size changes, or the form padding/margin changes, the scroll positions of containers in the content pane may be placed in an inconsistent state.  I have tried to cover a few spots where this happens, and "reset" the scroll positions in those cases.   It should fix this issue.
