### ISSUE TITLE
picker sluggish and hard to read on UWP device

### ISSUE THREAD

**Issue by pollaris** [codenameone/CodenameOne#2478]
When ported to a UWP device the picker is sluggish.
The new picker mode tries to fill the screen and
will not cancel on portrait mode. 
The cancel and done buttons are whiter on white and hard to read.
(I am using native project mode.)
The old picker mode worked well, centering the picker
on the screen with no problems selecting.

**Comment by shannah** [comment]
I have just committed some pretty big changes that should resolve this issue.  Rather than just reverting to old picker behaviour on UWP, I chose to fix the new lightweight picker so that it works better in UWP.  I have changed the buttons so they are more visible, and I've improved scrolling performance so that it is smoother.

I have also added an option in the Simulator in the Skins menu: "UWP Desktop Skin", which will simulate the look of the app when running on UWP.

**Comment by pollaris** [comment]
I just tested on the simulator, and the cancel and done buttons are visible.  When run on a physical device (Acer or Lumia) the cancel and done buttons are still whiter on white when using native mode.

**Comment by shannah** [comment]
The changes won't be available until the next server update on Friday.

**Comment by pollaris** [comment]
Thanks for your help

**Comment by pollaris** [comment]
When run on a physical device (Acer or Lumia) the cancel and done buttons are still whiter on white when using native mode.  UWP Desktop.skin shows black on white.

**Comment by shannah** [comment]
Looks like I forgot to commit the changes to the binaries repo so they didn't make it into the last server deploy.  I have committed them now, so they'll be there for the next server update on Friday.

**Comment by pollaris** [comment]
The new picker is operating smoothly now on UWP device.  Thank you for your help.  -Russ
