### ISSUE TITLE
[BUG] Validator issues on Android

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2484]
About the testcase (code and screenshots) reported at the start of this discussion:
https://github.com/codenameone/CodenameOne/issues/2472
two bugs about the Validator on Android 7 still exist (maybe they are correlated):

- the "First name" field always validates, also with an invalid input (that is a String of only one char). This is an old bug that I reported here: https://github.com/codenameone/CodenameOne/issues/2470

- new bug just discovered: after installing on Android 7 the app "UiBindingBug" (code linked above), the Validator didn't worked at all. It started to work only on the second run of the app.

**Comment by shannah** [comment]
Working with your test case, I found that:

1. Validation works fine when tapping out of a text field (e.g. if you tap a different text field, or just tap elsewhere in the form).
2. Binding/Validation doesn't occur when pressing the "Next" button in the keyboard.

I was not able to to reproduce your 2nd bug "the Validator didn't worked at all. It started to work only on the second run of the app."  I suspect that this was just a red herring, and that you were exclusively using the "Next" button the first run, and then used a different flow for the 2nd run.

This issue is now resolved.
