### ISSUE TITLE
RFE: request for better looking on zoom-in (javascript port)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2497]
I'm not sure if this an RFE or a bug report... however, an issue of the javascript port is that if the user zoom-in the page, the text seems blur or grainy. To see a good-looking page, the user has to reaload the page after the zoom-in. Tested with Firefox and Chrome.

For example: https://www.codenameone.com/demos/StringEncoder/index.html

### No Zoom (initial loaded page):
![nozoom](https://user-images.githubusercontent.com/1997316/43884171-af7d1186-9bb5-11e8-8d3e-91b9e133a65d.png)

### After zoom-in (using the default browser zoom-in):
![afterzoom](https://user-images.githubusercontent.com/1997316/43884191-bd978ddc-9bb5-11e8-9530-2ec29abf0615.png)

### After reloading the page:
![afterreloading](https://user-images.githubusercontent.com/1997316/43884201-c49aa448-9bb5-11e8-870e-0ea716ac051c.png)

**Comment by shannah** [comment]
The way it currently works is optimal, but not optimum. I.e. the way it currently works:

1. On page load, cn1 checks the browser's pixel density, and uses this to generate sensible defaults for font sizes, and the device density (used for things like multi-images).   The pixel density it retrieves here is cached and used until the page is reloaded
2. If the user zooms in or out, the browser will actually update its pixel density value to reflect the zoom level - however, we ignore these changes (until page reload) because updating our canvas density to synchronize the changes would result in an inconsistent state (e.g. font sizes, and multi-images, were loaded with the densities we retrieved on page load, but the canvas density wouldn't match).
3. Therefore, we rely on the browser itself to scale out content, which is consistent, and works across the board (for all of our UI) - but has the down-side that it is actually being "scaled" - and becomes blurry.

There are no "small" changes that I can think of that will yield a better result than what we have.  

In order to achieve anything better than what we have, I would need to keep track of the zoom changes myself, and then apply this to all coordinates that are passed between the app, and the native layer.  This includes events, graphics drawing primitives, native components, etc...  Very high likelihood of regressions in a change like this -- we'd likely be tracking down bugs for a long time.

**Comment by codenameone** [comment]
Can we detect the zoom action and provide a callback on that?
This would allow a user to implicitly reload the page on zoom or provide a notification to the user.

**Comment by shannah** [comment]
We can detect it based on when the pixel density changes, at least in Chrome.  I haven't tested other browsers, but it is likely that they don't all do it the same way.  This SO thread suggests that it's a bit of a mess:  https://stackoverflow.com/questions/1713771/how-to-detect-page-zoom-level-in-all-modern-browsers

Let's assume for the moment that we can reliably detect zoom changes cross-browser.  Reloading on zoom seems like a can of worms, as the user doesn't expect zooming to cause a reload - causing him to potentially lose everything he's been working on.

I also experimented with just adjusting the canvas density on zoom - which almost has the effect of disabling zoom altogether.  The problem with that is that native widgets and text fields will be "zoomed" still, creating inconsistencies between light-weight and native parts of the UI.

In chrome, zooming, triggers a resize event.  I could potentially add a display property that returns the current zoom level, if the developer wanted to know.  However, I worry that that would encourage "hacks" which aren't sustainable going forward.  The zoom level that I provide would be based on heuristics and not an official W3C API, so it is possible that keeping an accurate value across all platforms would be difficult - and it could make for compatibility issues in the future if we do decide to move forward with comprehensive zoom support.

**Comment by codenameone** [comment]
OK. Unless it's crucial I don't think we should do something.
