### ISSUE TITLE
BoundTableModel

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2499]
I need to build my app to Javascript to test on the production environment your implementation of the BoundTableModel (I've done the first tests in the Simulator and they seem ok). I know that your BoundTableModel will be integrated in the build server next week and that, in the while, I can insert it in my project as a new class.

However, I cannot insert in my project as a new class because these lines (the access is private):
`return pb.getPropertyIndex().get(n).get();`
`pb.getPropertyIndex().get(n).setImpl(o);`

Any suggestion?

**Comment by codenameone** [comment]
I pushed out a server update. This won't be available in the client libraries but since you compile against the code it shouldn't matter. It would be available for the cloud build so your calls would be resolved and you can use this API now.

FYI for the record this should work as is from any package `pb.getPropertyIndex().get(n).get();`.
`setImpl` is package protected but you can probably use `set()` instead for most cases. You'd just need to downcast to `Property`.
