### ISSUE TITLE
[Javascript Port BUGs] Alignment issues

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2527]
I noted that, when I port my apps to Javascript, the Components inside other Components (like the text inside a Button, or like the icon inside a FloatingActionButton, or like the rotating arrows inside an InfiniteProgress) are not aligned correctly.

This is a very easy test case with the default native theme:
```
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));
        Button button = new Button("Tap me");
        button.getAllStyles().setFont(Font.createTrueTypeFont("native:MainBlack", 7));
        button.getAllStyles().setBorder(Border.createLineBorder(1, ColorUtil.BLACK));
        button.addActionListener(l -> {
            Dialog infiniteProgress = new InfiniteProgress().showInfiniteBlocking();
            UITimer.timer(3000, false, infiniteProgress, () -> {
                if (infiniteProgress.isVisible()) {
                    infiniteProgress.dispose();
                }
            });
        });
        hi.add(button);
        FloatingActionButton.setIconDefaultSize(7);
        FloatingActionButton.createFAB(FontImage.MATERIAL_ADD).bindFabToContainer(hi.getContentPane());
        hi.show();
```

This is how it appears on the Simulator with iPadAir2.skin:
![alignment_ipad](https://user-images.githubusercontent.com/1997316/44394225-00ccb480-a537-11e8-95e3-49c7c0269ceb.png)

This is how it appears on the Javascript port with Chrome (https://cloud.codenameone.com/build/getData?m=result&i=e9211cb5-c2b8-438b-bff5-0400c75dd18d&b=a6dc0d82-9903-434e-abfc-a007bf5b3c83&n=preview1169276861364390594.html):
![alignment_chrome](https://user-images.githubusercontent.com/1997316/44394243-088c5900-a537-11e8-9dc0-3d0c0c2b9253.png)

As you can see, that "Tap Me" text of the Button is not centered in the Border, the icon "+" is not centered in the FAB and, if you click on "Tap me", you can see that the rotating arrows of the InfiniteProgress don't rotate correctly (because the center of the rotated icon moves during rotation).

Moreover, there are differences, in this test case, on how the FAB is rendered in Chrome (it's small with a noticeable alignment issue) and Firefox (it's bigger with a less noticeable alignment issue). The alignment issue of the text inside a Button is the same on Firefox and Chrome.

**Comment by codenameone** [comment]
If I recall correctly this is due to a firefox bug/misbehavior in canvas to which there was no workaround. I wonder if something changed since the last evaluation of this issue?

**Comment by jsfan3** [comment]
@codenameone This issue is not specific of Firefox. It's worst on Chrome than on Firefox.

**Comment by shannah** [comment]
I built your test case, but it looks different.

![image](https://user-images.githubusercontent.com/2677562/44462514-aaf51c80-a5c9-11e8-99a1-13464b6b9ad0.png)

Icon still not centered vertically, but it doesn't look as off as yours.

**Comment by shannah** [comment]
I modified the strategy for calculating font height in a way that is more accurate.  The result of this test case for me now in Firefox is

![image](https://user-images.githubusercontent.com/2677562/44465199-c06e4480-a5d1-11e8-91e0-df8c3d5620aa.png)

Will be available as part of next update

**Comment by jsfan3** [comment]
Thank you very much! However, have you also done a test on Chrome? I ask you that because the appearance of the icon was a lot worse on Chrome than on Firefox, and that is a probably the cause of the different screenshot you got.

**Comment by jsfan3** [comment]
More precisely, Chrome on Linux.

**Comment by shannah** [comment]
I have tested on Chrome and Firefox on Linux, Windows, and Mac.  This is actually a fairly major overhaul of how the port draws strings and deals with font metrics.  We used to use the "top" text baseline for drawing text in the canvas since it is more consistent with way our own Graphics contexts work, but Chrome and Firefox work differently (Chrome seems to add an offset to the text that firefox does not).  I have changed it to use the alphabetic baseline now, which seems to work the same across browsers.  That just required me to produce better estimates for font height, ascent, and leading.

I changed to a different strategy for measuring font metrics.   Previously, we estimated ascent by simply using the width of the letter 'M'.  In many cases this simple heuristic worked fine.  With material fonts it didn't work fine - which is a large part of the reason for the alignment problems in the FAB.  The new strategy makes use of a pixel image at various vertical-align values, to measure the probable ascent.  This seems to yield much better results.

**Comment by jsfan3** [comment]
Thank you for the explanation and for the fixes :-)

**Comment by jsfan3** [comment]
Today I saw the new alignment: it's a lot better! ;)

However, there is something that could be more improved: the text inside TextField _(I tried the TextFields automatically generated in a TextModeLayout with TextComponents)_, that at the moment is aligned to the top during the writing and then aligned to the center when the focus is lost.
