### ISSUE TITLE
image processing internals

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2589]
I'm proposing a few small changes in the internals of the Image api to facilitate image processing
applications.   The problems I'm addressing are that (1) "getRGBCached" is basically useless for any 
dynamically changing image, because it's cache is never cleared except unpredicably by the garbage
collector.  (2) getRGB() the uncached version, thrashes memory because it always allocates a new
array.  Screen arrays are 8mb or more, and can change hundreds of times a second.

To fix these, I would change the internal function getRGBImpl to be passed the array it uses,
add a second public getRGB method that passes the array, and uncache the getRGB cache
when toRGB or getGraphics is called.  There may be other places where uncaching is logically
required.

If you agree in principal to these changes, I'll prepare a push request.

**Comment by codenameone** [comment]
On the surface this seems fine and can even fit into most implementation calls which already have a getRGB() array API. However, notice that you can't change the signature of existing methods. So you should create new methods to satisfy your requirements.

**Comment by ddyer0** [comment]
what about changing from unclassified to public ?

**Comment by codenameone** [comment]
Normally this isn't a problem but you should check why we made a method package private.
I'm guessing you mean our `getRGB` method that accepts an array and a huge set of arguments... Don't make that public.

The reason it isn't public is that it doesn't work. It's implemented incorrectly in most platforms because it has too many nuances. The only case where it works correctly on all platforms is the case we invoke from `getRGB()` which is the case that extracts all the pixels of the image.

**Comment by ddyer0** [comment]
closed, push request accepted.
