### ISSUE TITLE
Popups don't work on Android

### ISSUE THREAD

**Issue by thomas-hutterer-tik** [codenameone/CodenameOne#2594]
Background shines through and controls don't react on touch
![fymg4702](https://user-images.githubusercontent.com/1253130/47461163-7297d780-d7e0-11e8-8fc6-f3f1b3e77440.jpg)
![hasd2772](https://user-images.githubusercontent.com/1253130/47461164-7297d780-d7e0-11e8-9d12-7f79f9ccf525.jpg)

**Comment by codenameone** [comment]
This happens because popups only have styling on iOS by default. On Android and other OS's there is no builtin design for popups. As a workaround you can just style the PopupDialog with an arrow image border which is a bit challenging. Or just set the UIID of the PopupDialog to Dialog.

Normally we include a decent default design in the base theme and all OS's inherit that. However, including images for the arrow and border in the base theme seems like a bit much. A better solution would be a new border type that includes the arrow behavior so we can define the default styling for everyone.
