### ISSUE TITLE
Codename One benchmark?

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2678]
Does a Codename One benchmark exist?

While I'm developing a complex app, it is becoming increasingly slow in the javascript port _(quite unusable)_, _while it continues to run smoothly in native apps_. I suspect that the problem is the various listeners connected to the tapping and the dragging (they are in all the Forms), and the mathematical calculations (also trigonometric functions) that they make. I use various layers of layeredPane and a Form within another Form.

I wonder if there is any way to investigate what specifically slows down the web-app on Android Chrome _(on iPhone there are no problems... but of course the hardware is different)_. For example, do you have a benchmark that tests all (or almost all) the Codename API in thousands of executions and compare the time results to discover if an API is a bottleneck in a specific platform or browser?.

Thank you

**Comment by shannah** [comment]
Performance is tricky.  Chrome provides some profiling tools but I haven't found them all that helpful.  Their [performance-tuning instructions](https://developers.google.com/web/tools/chrome-devtools/rendering-tools/) include lots of details that aren't relevant to CN1 apps  (layout and CSS, etc...).

I have generally had to work out performance issues by trial and error - and on a per-browser basis.  Sometimes I would run across things that kill performance in a browser for no good reason, - and won't affect any other browsers.

If I run into a place where performance is poor, I try to narrow down the problem as much as possible - make the problem as small as possible.  Ideally some sort of toggle on/off where if something is "on", then performance is bad, and if it is "off", performance is good  (i.e.  If we do *this*, then is kills performance).

That said:

1. `long` arithmetic (and by extension Date arithmetic) is slow in javascript because long needs to be emulated.
2. Desktop generally has good performance across the board.
3. iOS has had good performance on the JS port going way back.. Even my iPhone 4S works OK (but not great).  My iPhone 6S, and IPad Air 2, both have very good performance.
4. It is known that Android is lagging well behind iOS on hardware.
5. My most recent Android device right now is quite old (Nexus 5).  It works OK, but is noticeably slower than any of the iOS devices I have.

**Comment by jsfan3** [comment]
Thank you for these tips, I’m investigating...

**Comment by jsfan3** [comment]
Do you know some reliable app or method to measure the CPU usage of a Codename One web-app while it runs on Android Chrome?

**Comment by shannah** [comment]
You should be able to use the Chrome dev tools to do this:

* https://developers.google.com/web/tools/chrome-devtools/remote-debugging/
* https://developers.google.com/web/updates/2016/12/devtools-javascript-cpu-profile-migration

**Comment by jsfan3** [comment]
After two weeks, I've just found the solution of my problem: I had two `myButton.repaints()` in my code, the first one was useless, I removed it and the web-app started to work correctly... before this change, the web-app was too much slow on Chrome Android, almost unusable. I never guessed that the problem was stupid like that. I spent whole days making optimizations that I could avoid.

**Comment by shannah** [comment]
Glad to hear you figured it out.  These are the most difficult types of problems to debug.  Can you provide some more information about the context of the extraneous repaint call?  Is it possible that there was some kind of repaint loop, where painting it triggers another repaint call?  If we can get a test case out of this, I might be able to guard against whatever was happening, or at least provide some useful debugging information.

**Comment by jsfan3** [comment]
I have a Form with a `PointerDraggedListener` that does several complex calculations to move some Components in the LayeredPane when the user does the dragging.
This `PointerDraggedListener` calculates and sets the new positions of several Containers, then `repaints` each Button contained in these Containers and finally `repaints` the Container that contains the Containers that contains the Buttons. Of course `repaint` each Button is not necessary, it's enough to `repaint` the global Container. These `repaints` occurs during the dragging, that means tens (or hundreds?) times per second. As I told, the performance problem was only in the Jvascript port, while the native apps were not slowed down by extra `repaints`.
