### ISSUE TITLE
InteractionDialog.showPopupDialog(Component c) is not disposed

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2684]
The Javadoc of `InteractionDialog.showPopupDialog(Component c)` tells: «A popup dialog is shown with the context of a component and its selection, **it is disposed seamlessly if the back button is pressed or if the user touches outside its bounds**.»

I tried that, but if I tap  outside its bounds it's not disposed. Tested in the Simulator with Android and iOS skins.

Test case:

```
        Form hi = new Form("Hi World", BoxLayout.y());
        Button name = new Button("Name");
        addOverflowMenu(name);
        hi.add(FlowLayout.encloseCenter(name));
        hi.show();
```

```
     public static void addOverflowMenu(Button button) {
        button.addActionListener(e -> {
            Button op1 = new Button("First Option");
            Button op2 = new Button("Second Option");
            InteractionDialog d = new InteractionDialog("", BoxLayout.y());
            d.addAll(op1, op2);
            d.showPopupDialog(button);
        });
    }
```

**Comment by codenameone** [comment]
Actually I think that's a copy/paste mistake in the docs. Something left over from the method signature of the Dialog version

**Comment by codenameone** [comment]
This is under documented because it sucks. Currently you need to define these theme constants and an image border:
`PopupDialogArrowBool`, `PopupDialogArrowBottomImage`, `PopupDialogArrowTopImage`, `PopupDialogArrowLeftImage`, `PopupDialogArrowRightImage`.

This kind of sucks and we'd like to fix it by introducing a border shape that supports arrow. This can possibly be added as a feature to `RoundRectBorder`. We just didn't get around to do this.

**Comment by shannah** [comment]
I have posted the Popup arrow part as a separate issue.  https://github.com/codenameone/CodenameOne/issues/2689
