### ISSUE TITLE
RFE: API to choose resolution to capture photos

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2702]
Same as https://github.com/codenameone/CodenameOne/issues/2696, but about photos.

The current API `capturePhoto(int width, int height)` simply scales the photo after taking it at the maximum resolution. The problem is that scaling a full sized photo to the resolution that I want requires about 2-3 seconds on my Android (and half second on my iPhone), during that the app is frozen. So scaling a photo is cpu intensive, it's better to take it at the wanted resolution (if it's known).

Reason for that I use scaling: uploading the taken photo requires about 35-40 seconds with 3G or my ADSL connection, while uploading a scaled photo (saved as JPEG with quality 0.6) requires 2-3 seconds (and the result is enough good). 

Same issue and same purpose of https://github.com/codenameone/CodenameOne/issues/2696, with the request of an API to get the available resolutions and another API to take a photo sync or async at the wanted resolution (or in a range of resolutions, if the list of supported resolutions is unknown).

Thank you

**Comment by jsfan3** [comment]
_(To be more precise: the scaling of a photo requires so much time on the Javascript port, while on native apps is a lot faster)_

**Comment by codenameone** [comment]
I think a better approach would be to fix camera kit. It already supports this functionality to some degree.

**Comment by jsfan3** [comment]
Camera Kit doesn't support Javascript _(can you make Camera Kit working also in the Javascript port?)._

Thank you for your support, I understand that my RFEs about photos and videos are NOT trivial! :)

**Comment by jsfan3** [comment]
If I remember correctly, Camera Kit allows to place the live preview in the `CENTER` of a `BorderLayout.CENTER_BEHAVIOR_TOTAL_BELOW`, so the UI can be customized. Is that true?

If it's so, a Camera Kit cn1lib fixed, improved and well working on Android, iOS and Javascript _(with all APIs documented and implemented in a cross platform way)_ will be a **huge improvement** and a big added value to Codename One.

**Comment by codenameone** [comment]
Camera Kit is an Android library which we wrapped. We then implemented the iOS version and aligned to that API. I'm assuming it's possible to do so for JavaScript too. 
Assigning it to @shannah for adding that support into the library

**Comment by shannah** [comment]
@codenameone The sample code in the [readme for the CameraKit library](https://github.com/codenameone/CameraKitCodenameOne/blob/master/README.md) doesn't appear to call the `start()` method, even though the docs say that you need to call `start()` before using the camera.  Is there a more recent/complete demo I can work with in porting the API to Javascript?

**Comment by codenameone** [comment]
This is the actual demo code: https://github.com/codenameone/CameraKitDemo/blob/master/src/com/codename1/camerakit/CameraApp.java

**Comment by shannah** [comment]
I have added CameraKit support for Javascript and Simulator.  Since neither support all of the features, Here is an [updated demo](https://github.com/codenameone/CameraKitCodenameOne/blob/master/CameraKitDemo/src/com/codename1/camerakit/demo/CameraKitDemo.java).  It is the same as the other demo, except this keeps a reel on the side of the screen where captured images and videos are shown.

The simulator only supports image capture - not video capture.  And Javascript support varies by platform.  The latest development version of Safari mobile should support video capture, but prior versions do not.  Android Chrome supports both video and image capture.

I have added a method `supportsFeature()` which can be used to see if a specific feature is supported.

The updated plugin in the the CodenameOneLibs repo so should be available in CodenameOneSettings soon.

**Comment by jsfan3** [comment]
Thank you!

Help me to understand: to capture a video at the wanted resolution should I use the Video Capture Constraints that you developed some days ago, while to capture a photo at the wanted resolution should I use the CameraKit cn1lib?

**Comment by shannah** [comment]
Depends on your requirements.  VideoConstraints API is less flexible, but easier because you don’t have to set up the UI for camera usage.  CameraKit is more flexible, but you need to set up the UI for capturing

**Comment by jsfan3** [comment]
But... CameraKit is bugged and not working, as reported here:
https://github.com/codenameone/CodenameOne/issues/2596

Had you fixed all the bugs?

**Comment by codenameone** [comment]
No, this is still pending.

**Comment by jsfan3** [comment]
@shannah Because the CameraKit is unusable, can you add APIs to Codename One to choose resolution to capture photos, in a similar way to what you did for videos?

As I wrote and explained at the starting of this discussion, the current API `capturePhoto(int width, int height)` is a very bad API.

**Comment by shannah** [comment]
Android doesn't seem to allow you to choose an image size with via the MediaStore intent.  All examples I can find suggest doing the resize after the image is received.  I can try to address the scaling performance.  E.g. maybe it's the *way* the scaling is occurring that is taking so long, and there may be a more efficient method.

Otherwise, I'd be looking at implementing the capturePhoto() method using a lower-level camera API - and if I'm doing that, I might as well get CameraKit working.

**Comment by jsfan3** [comment]
Thank you!

**Comment by jsfan3** [comment]
About the performance of scaling, please consider that the worst performance are on Javascript.

**Comment by shannah** [comment]
So that figure of "2-3 seconds".  Is that on Android native, or Javascript running on Android device?

**Comment by jsfan3** [comment]
Javascript running on Android device. See my second comment in this discussion.

**Comment by shannah** [comment]
You can use the `javascript.useGetUserMedia` display property to cause Capture.capturePhoto() to use getUserMedia on iOS and Android.  I have added a sample to demostrate this:

https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/JavascriptCapturePhotoSample/JavascriptCapturePhotoSample.java

Unfortunately, I found a few issues when I initially tried this sample now, so I made a couple of changes which will be available in the next update.

**Comment by jsfan3** [comment]
ok

**Comment by shannah** [comment]
CameraKit should resolve this issue.
