### ISSUE TITLE
iOS Certificate Wizard and the soon required two factor authentication

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2706]
I've just received the following email: will the two factor authentication broke the iOS Certificate Wizard? I suppose that it will made impossible to build Codename One apps for iOS without having an Apple device, because I read here that the two factor authentication requires an Apple device: https://support.apple.com/HT204915

> In an effort to keep your account more secure, two-factor authentication will be required to sign in to your Apple Developer account and Certificates, Identifiers & Profiles starting February 27, 2019. This extra layer of security for your Apple ID helps ensure that you're the only person who can access your account. If you haven't already enabled two-factor authentication for your Apple ID, please learn more and update your security settings.

**Comment by codenameone** [comment]
The build won't be impacted and installation shouldn't be impacted either. This will impact the process of generating a certificate (which you don't do every day) and it will probably impact the process of adding a new version to itunes.
Apple is effectively demanding that you buy a recent iDevice in order to even login to their service. You could probably buy a cheap iPad to solve that problem when it actually arrives.

**Comment by jsfan3** [comment]
Ok, I misunderstood what Apple asked. This morning I enabled the two-factor authentication on my iPhone and then I tried to use your ios certificate wizard: it works as expected, because your wizard asks for the confirmation code. I feared that there were more complex changes, but it was all simple :-)
