### ISSUE TITLE
Tabs component in the new GUI builder bugs

### ISSUE THREAD

**Issue by kennygli** [codenameone/CodenameOne#2718]
I was able to create a new tab with two default tabs already added. I could modify it. It seems to work. But I cannot add additional tabs. It worked in the old GUI builder.

Can someone help? I'm using the codenameone 5.6.

**Comment by shannah** [comment]
I'm walking through this issue.  Here is what I've done.

1. Dragged a Tabs component onto the canvas.
2. Clicked the Content menu above the tabs, and selected "Edit Tabs"
![image](https://user-images.githubusercontent.com/2677562/54205161-02d67080-4493-11e9-9b5e-f3bdb3c76e23.png)
3. Tried to enter a new tab by typing into the empty field in the last row of the form. 
![image](https://user-images.githubusercontent.com/2677562/54205219-24cff300-4493-11e9-91c4-611223968102.png)
4. It shows a red "X" on the right side of the tab name text field. 
![image](https://user-images.githubusercontent.com/2677562/54205268-43ce8500-4493-11e9-9773-735d9b5482e0.png)

Are these steps the same as yours?  Is this the same problem?

Workaround:

1. Leave the Tab name field empty, and press the "+" button.  This will add a new row with a blank field.
2. Enter the tab name in that field.
3. Press "Apply".

That will add the tab.

Working on fixing the issue so that the workaround isn't necessary.  Please let me know if your issue is different
