### ISSUE TITLE
Regression on TextField  display when text is larger than TextField

### ISSUE THREAD

**Issue by 3lix** [codenameone/CodenameOne#2722]
The following problem is back  https://github.com/codenameone/CodenameOne/issues/2330

You can test with this code.
```
 Form hi = new Form("Hi World", BoxLayout.y());
 hi.add(new Label("Hi World"));
 hi.add(new TextField("A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"));
 hi.show();
```

**Comment by codenameone** [comment]
On which OS?
Do you use any special build hints?
Do you derive from the native theme?

**Comment by 3lix** [comment]
I see it on Android + Simulator 
tested on a brand new project with the code above.

**Comment by codenameone** [comment]
FYI Looking at the code I still see the fix from @shannah in the code

**Comment by shannah** [comment]
The reason is that the textfield is set to paint from the current cursor position.  It seems that the default cursor position is the end of the text.  I have made a change so that TextFields will always paint from position 0, unless they have focus, in which case it will take the current cursor position into account.

Even with this change, your example will display from the end, because with only a single text field, it is given focus by default.

E.g. Even after the fix, your test case looks like:

![image](https://user-images.githubusercontent.com/2677562/54280798-8f496780-4555-11e9-9e65-2b26a98f531b.png)

But if you add a 2nd text field, it looks like

![image](https://user-images.githubusercontent.com/2677562/54281397-e439ad80-4556-11e9-8a38-779b406b5f82.png)
