### ISSUE TITLE
Capture a video on Android

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2736]
Please look at this video:
https://www.informatica-libera.net/videoLavoro/capturingVideoAndroid.mp4

It is a native Android app (it's the test case reported here: https://github.com/codenameone/CodenameOne/issues/2696). The problem is that Android asks to open the just recorded video with an external app (that crashes, as you can see in the video, but other times I got a blank black screen). @shannah gave a short answer to this issue (https://github.com/codenameone/CodenameOne/issues/2696) saying that it depends by the Android version.

I tested on Android 7 on this phone: https://www.gsmarena.com/huawei_honor_6x-8388.php

Is it possible to make Android to replay the just recorded video without the need of an external app (like on iOS)? The current behaviour is a bad user experience.

**Comment by codenameone** [comment]
Do you have the device logs from this? There's probably an exception in DDMS when this happens.

**Comment by shannah** [comment]
I found these related issues in Google searching.

https://stackoverflow.com/questions/50214491/mediastore-action-video-capture-crashes-app-when-playing-recorded-video-from-pre

https://stackoverflow.com/questions/29280080/mediastore-action-video-capture-crashes-camera-app-if-device-is-portrait?lq=1

https://teamtreehouse.com/community/choose-pic-and-video-works-take-pic-and-video-crash

The gist is 

1. The camera app that you are using to handle the ACTION_VIDEO_CAPTURE intent has a bug.
2. Try using a different camera app as your default app for handling that intent.

Found [this page](https://www.howtogeek.com/howto/43135/how-to-change-the-default-application-for-android-tasks/) that describes how to change your default camera app.

Since all we do is send the intent, we can't really do much.  As mentioned in some of those posts, there's no flag for "only open in apps that don't have a bug" in the intent.
