### ISSUE TITLE
RFE: "tap to select" in (lightweight and native) string pickers

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2740]
Can you add an API to make the current "lightweight string `Picker`" and "native string `Picker`" selecting a string tapping on it (without the "ok" button)? The same request is for `PickerComponent`.

Thank you

**Comment by codenameone** [comment]
I don't think we should do that on the native version. It's impractical to maintain that. But it's probably possible to add a special mode to the lightweight version.

**Comment by shannah** [comment]
Do you have any examples of controls that work this way?  I'm not entirely clear on how this would need to work.  Some questions:

1. Can the user simply tap on one of the non-selected options in order to select it, or do they need to scroll the option they want to be "selected", and then tap on that option again?  Both of these leave something to be desired.  Being able to just "tap" on another item feels weird since the spinner is 3D, and all but the currently selected option is rendered vertically compressed (3d perspective).  Having to tap again on the selected item seems less intuitive than just pressing "Done" once you've changed the selection.

Can you walk me through exactly how you see this working from the user's perspective?

**Comment by jsfan3** [comment]
You're right, this request is not from me but from my employer. I'll ask him to be more clear about this request and then I'll write here again.

**Comment by jsfan3** [comment]
There was a misunderstanding with my employer: he wants pickers that are graphically different from both native pickers and lightweight pickers. I'm going to try to develop them by myself. Now I close this RFE because it's not what I actually need.
