### ISSUE TITLE
RFE about UIFragment

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2743]
I've just read your blog post: https://www.codenameone.com/blog/introduction-to-uifragment.html

Yes, you're right: sometimes the amount of work to creare an UI is frustrating and reading the Java code is not intuitive when the UI is not trivial. Your new approch seems very interesting. 

I would like to ask you to evaluate this RFE: is it possible to automatically set the name of each Component equal to its placeholder name?

This is your first example in the blog post:
```
Form f = new Form("Test Form", new BorderLayout());
f.add(
    BorderLayout.CENTER,
    UIFragment.parseJSON("{s:{n:{flow:[$myTextField], align:right}, s:$submitButton}}")
        .set("myTextField", new TextField())
        .set("submitButton", new Button("Submit"))
        .getView()
);
f.show();
```

I mean that this code could do `.setName("myTextField")` and `.setName("submitButton")` automatically. In this case, the name of the Components will be different from the placeholders only if `.setName()` is added manually.

The advantage of this RFE is the use of the "Component Inspector" of the Simulator, that sometimes is very hard to use when there are a lot of unnamed Components.

**Comment by shannah** [comment]
Good idea.  I have added this feature as you have described it.  I.e. `set("submitButton", new Button("Submit"))` will call `setName("submitButton")` on the button if the button doesn't already have a name set.

I have also added support for the `name` attribute in the JSON and XML notation so that you can set the name on containers in the fragment also.

e.g.

~~~~
UIFragment.parseJSON("{name: 'OuterBorder', s:{n:{flow:[$myTextField], align:right name:TextWrapper}, s:$submitButton}}")
        .set("myTextField", new TextField())
        .set("submitButton", new Button("Submit"))
        .getView()
~~~~

In that example, the root view will have name "OuterBorder", and the nested FlowLayout container will have name "TextWrapper".   The `new TextField()` will have name "myTextField", and `new Button("Submit")` will have name "submitButton".

**Comment by jsfan3** [comment]
Thank you very much!

Can I suggest to update the blog article? :)
