### ISSUE TITLE
RFE: make text copyable from web-app

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2750]
One of the main differences between a standard web site and web-app made with Codename One is that the text cannot be selected and copied.

Is it possible to make the text (of Label, Button, SpanLabel and SpanButton) copyable?

For example, I just published a very easy web-app that simply shows a sentence for every day of the year: https://www.informatica-libera.net/giorno-per-giorno-ikeda/
I suppose that the most of users expect that the text could be selectable and copyable (from desktop browsers and mobile browsers).

As side note, only iPhone users expect and know the tensile dragging, while when the app is open from a desktop browser probably the tensile dragging is undesirable.

**Comment by codenameone** [comment]
You can use isDesktop() to determine the desktop/phone browser.
The text is no longer there when you try to select it since we use the canvas API to draw the UI. In that sense we show you an app and not a website. You can copy text from a textfield/area since we use a native widget to provide editing in that case.

**Comment by jsfan3** [comment]
Thank you Shai, you're right.

However I would ask to you this fact: if I use a `TextArea` with `.setEditable(true)` and `.setFocusable(true)`, the text can be selected, copied and modified (as expected). But if I set `.setEditable(false)` and `.setFocusable(true)`, the text cannot be selected or copied. I'm not an expert of canvas and I don't know the details of the javascript implementation of Codename One, but it could be nicer if the text can be selected and copied (but not modified) if `.setEditable(false)`.

This RFE is not urgent or crucial, I'm only asking to evaluate if it's possible. Sometimes it could be desirable, sometimes it couldn't, it depends by what we are developing.

I read this discussion about copying text from canvas, it seems very difficult, but I don't know if it could be easier with Codename One:
https://stackoverflow.com/questions/1451635/how-to-make-canvas-text-selectable

If it's not possible or too much complicate, don't worry and close this RFE.

**Comment by shannah** [comment]
It wouldn't be too hard to make non-editable text fields behave the same as editable text fields (i.e. use a native overlay text field when focused), only the native text field would be non-editable.  Would this be sufficient for your use case.  Most of the time this behaviour wouldn't be desirable, so I'd want to add some sort of flag to enable it.

**Comment by jsfan3** [comment]
Ok, thank you!
In this case, the ideal situation is that the user will not notice any difference from copying the text from a standard web page or from the web-app... (or at least to make the user experience as close to this as possible).

**Comment by shannah** [comment]
In that case, the native-overlay solution would be insufficient.   To achieve that goal we'd probably need to develop light-weight text selection support in CN1.  Easy to do.  Hard to do well.

**Comment by shannah** [comment]
I opted to go with a light-weight text selection implementation.  The benefit of this is that it will work cross platform without any painful implementation stuff.  The down side is that there will be slight differences in behaviour between "native" text selection and CN1 app text selection.  As with anything, we can narrow these differences as time goes on.

I'm almost ready to push this out.  Just a few touch ups and documentation remain.  It will support both "desktop-like" behaviour and "mobile/touch-like" behaviour.  Runtime behaviour is dictated by a platform implementation flag - so that we can choose the best one for the platform.

Desktop-like behaviour works with the familiar pointer press, drag over text, and release pattern.  Mobile/touch behaviour is initiated with a long press on a selectable element (e.g. label, uneditable textarea, etc..), and then provides handles to change the selection.

When in desktop mode, it will be tied in with the standard desktop menus and keyboard shortcuts.  In mobile/touch mode, it will provide custom popover buttons for copy.  We can use themes on these buttons to try to match the look of the native buttons as closely as possible.

I was hoping to get this out today so that it would be in tomorrow's update, but it's not quite ready, so it will be in next weeks update.

**Comment by jsfan3** [comment]
Thank you!

**Comment by shannah** [comment]
On Device:

![image](https://user-images.githubusercontent.com/2677562/56235196-cc64b600-603b-11e9-89db-cbe7b824a623.png)

On Desktop:

![image](https://user-images.githubusercontent.com/2677562/56235303-09c94380-603c-11e9-822d-eded0bd5d2bf.png)

[Sample](https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/TextSelectionSample/TextSelectionSample.java)

Some key points:

1. Text selection disabled by default.  Must be enabled per form using `myForm.getTextSelection().setEnabled(true)`
2. Labels, SpanLabels, TextFields and TextAreas all support text selection.
3. Labels and SpanLabels have text selection disabled by default.  Must enable using `setTextSelectionEnabled(true)`.
4. TextFields and TextAreas will have text selection enabled by default if `isEditable()` is false.  I.e. If you call `myTextArea.setEditable(false)`, this text field will support text selection.  You can disable text selection using `myTextArea.setTextSelectionEnabled(false)`.

**Comment by jsfan3** [comment]
Thank you, it seems great!
