### ISSUE TITLE
FlowLayout in LayeredLayout doesn't get sized correctly

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2751]
It is related to this closed issue #2720, but there seems to be a cause other than percentage insets. In the given sample I don't use any percentage values.
As soon as I set a preferred width of a LayeredLayout's child with a FlowLayout, the child isn't displayed properly.
In this sample imho all 20 dummy Components should be seen but they aren't (**Assuming that it's possible that we can set just one dimension of the preferred size and keep the other one being ignored**):

        fun dummyComponent(w: Int, h: Int) = Container().apply {

            preferredW = w
            preferredH = h

            ComponentSelector.`$`(this)
                    .selectAllStyles()
                    .setBgTransparency(255)
                    .setBgColor(randomColor())
                    .setMargin(5)
        }

        Form(LayeredLayout()).apply {

            val components = Array(20) { dummyComponent(40, 20) }

           
            val box = components.let { FlowLayout.encloseCenter(*it) }. apply {

                preferredW = 200
                
                ComponentSelector.`$`(this)
                        .selectAllStyles()
                        .setBgTransparency(255)
                        .setBgColor(ColorUtil.YELLOW)

            }

            (layout as LayeredLayout).setInsets(box, "auto auto auto auto")
            add(box)
            revalidate()

        }.show()

Result:

<img width="359" alt="Bildschirmfoto 2019-03-27 um 11 49 20" src="https://user-images.githubusercontent.com/5825645/55070422-847af080-5086-11e9-8554-e093811e5733.png">

**Comment by shannah** [comment]
This is not related to LayeredLayout.  It is just related to how FlowLayout calculates its preferred size.  You can see this by simply changing the form layout to BoxLayout Y.  You see something like 

![image](https://user-images.githubusercontent.com/2677562/55075677-d30d9800-5050-11e9-9ca3-c3acac70543e.png)

Basically, when you set the preferredW of the FlowLayout container, it is still calculating its preferred height normally.  Actually, what FlowLayout does is use its *actual* current width to calculate its effective layout height.  So instead of

~~~
box.setPreferredW(200);
~~~

do

~~~
Dimension prefSize = box.getPreferredSize();
box.setPreferredH(prefSize.getHeight());
box.setPreferredW(200);
~~~

And you get the desired result

![image](https://user-images.githubusercontent.com/2677562/55075902-5202d080-5051-11e9-8bac-b17212ebe012.png)

I have added a [test case](https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/LayeredLayoutTest2751/LayeredLayoutTest2751.java) for this to the Samples.  You can run it and modify it in the [SampleRunner app](https://github.com/codenameone/CodenameOne/tree/master/Samples).

**Comment by kutoman** [comment]
great thanks! I was looking for something alike
