### ISSUE TITLE
Display.getInstance().sendMessage on iOS and on Javascript

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2756]
The following code:
```
String email = "nospam@nospam.com";
Message message = new Message("");
Display.getInstance().sendMessage(new String[] {email}, "", message);
```
opens an app picker on Android 7, in my case it allows to choose Gmail or another email app. So it works fine.

But on iPhone X, it shows a Dialog with the title "No Mail Accounts" and the text "Please set up a Mail account in order to send email". That's not correct, because in that iPhone I have the apps "Gmail" and "Protonmail" used every day.

Moreover, the same code doesn't do anything on the Javascript port (tested on Android Chrome and on iOS Safari). I tested it inside an ActionListener of a Button.

**Comment by shannah** [comment]
Javascript doesn't implement this yet.  I'll add that.

On iOS, we use `MFMailComposeViewController` which seems to rely on the "mail accounts" in settings - closely tied to the Mail app.  I found many other threads on Google mentioning this same issue.  Some have suggested workarounds involving a fall back to actually opening the mail app in the system in such cases, rather than showing the mail composer inside the app.  I'll look into adding such a workaround here.

**Comment by shannah** [comment]
This is now implemented in the Javascript port.  It will be included in next update.
On iOS, it will now fall back to opening the mail app to send mail if accounts aren't setup in settings.  This will also be available in the next update.

**Comment by jsfan3** [comment]
Your fix is not included in the server update of today: the test code doesn't do anything on the Javascript port (tested on Android Chrome and on iOS Safari).

**Comment by jsfan3** [comment]
Solved: now this fix is included.
