### ISSUE TITLE
Localization on iPhone

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2772]
As described here:
https://stackoverflow.com/questions/55789002/codename-one-l10nmanager-getinstance-formatdatelongstyle-on-iphone/55789555#55789555

`L10NManager.getInstance().formatDateLongStyle(myDate)` doesn't work correctly on iPhone X with "General", "Language" = "Italiano" and "Zone" (Regione) = "Italia".

**Comment by shannah** [comment]
This is caused by a change to the way iOS handles localization in iOS 11.
https://stackoverflow.com/a/46206511/2935174

In iOS 10, currentLocale would always return the Locale in the user's system settings.  In iOS 11, it will only return that locale language if the app "supports" the language.

For now, I'm just going to change our iOS implementation of L10NManager to use the device's locale settings - i.e. to work as it did in iOS10.  I'm not sure if there are other down sides to not "supporting" other languages the native way.  If so, we may want to look at adding dummy localization files to the iOS app bundle as well.
