### ISSUE TITLE
RFE : Implementing a method to disable paging arrows in Lightweight Pickers

### ISSUE THREAD

**Issue by Nightbringer42** [codenameone/CodenameOne#2775]
As referenced [on StackOverflow](https://stackoverflow.com/questions/55712143/removing-up-down-arrows-from-lightweight-picker) it should be a way to disabling paging arrows in the Lightweight Picker. 

Here is a reminder of those arrows :
![](https://i.stack.imgur.com/Ufd7o.png)

The easier would be a boolean in the picker and/or a static default value. Can you add that ?

**Comment by shannah** [comment]
Since this request was precipitated by an observation that the prev/next functionality causes encoding errors, it would make sense to fix that "encoding errors" problem.

The prev/next buttons will appear as long as there is a previous or next component to tab to.  

I have added a [sample](https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/TabIteratorSample2775/TabIteratorSample2775.java) to the [SampleRunner](https://github.com/codenameone/CodenameOne/tree/master/Samples) to demonstrate this.  The gist is:

~~~~
$("*", myForm).each(c->{
    c.setPreferredTabIndex(-1);
});
~~~~

Will disable tabbing on all fields in the form `myForm`.
To renable on any particular component you would do:

`myComponent.setPreferredTabIndex(0)`

Please open a separate issue describing the encoding issue that you mentioned, and reference this issue.  I'm closing this issue for now.

**Comment by Nightbringer42** [comment]
Thanks for the fix, I didn't think about this.
Our main encoding problem come from the customers (human error). Some of them were saying those arrows were disturbing and wanted them removed. Now this is done, thanks !
