### ISSUE TITLE
FontImage.setMaterialIcon not applying specified size

### ISSUE THREAD

**Issue by rochanas** [codenameone/CodenameOne#2865]
Up until a recent update, FontImage.setMaterialIcon would take in a size parameter and correctly alter the icon for that size. Now it makes everything the same size. The following code produces 3 + symbols, of the exact same size. Picture attached for reference

Form f = new Form(new BorderLayout());
f.getAllStyles().setBgColor(0xffffff);
f.getAllStyles().setBgTransparency(255);

Container labels = new Container(BoxLayout.y());

Label numWorkoutsLabel = new Label();
FontImage.setMaterialIcon(numWorkoutsLabel, FontImage.MATERIAL_ADD, 1);

Label numWorkoutsLabel2 = new Label();
FontImage.setMaterialIcon(numWorkoutsLabel2, FontImage.MATERIAL_ADD, 2);

Label numWorkoutsLabel5 = new Label();
FontImage.setMaterialIcon(numWorkoutsLabel5, FontImage.MATERIAL_ADD, 5);

labels.add(numWorkoutsLabel).add(numWorkoutsLabel2).add(numWorkoutsLabel5);
f.add(CENTER, labels);

f.show();

![cno_bug](https://user-images.githubusercontent.com/25064795/61248134-b97f8180-a70f-11e9-864e-3da1804f5051.png)

**Comment by ThomasH99** [comment]
Shoot, this is due to an error in a pull request I made some weeks ago. 

In FontImage.setMaterialIcon(Label l, char icon, float size), the new API setFontIcon is mistakenly called with -1 instead of the size. The error is only in that one call (for a Label). 

I don't have access to fix that from where I am these days, but hopefully Shai or Steve can fix it. 

Very sorry about that.
