### ISSUE TITLE
[BUG] TextArea multiple bugs

### ISSUE THREAD

**Issue by ramsestom** [codenameone/CodenameOne#2894]
I am trying to have an UI that looks like this:
![expected_form](https://user-images.githubusercontent.com/636758/63730866-584de080-c86d-11e9-8794-7ee93614829f.png)
so it is composed of three TextAreas (the black boxes) with a Label in front of each. And the whole thing should be rendered in the same line and centered horizontally on the screen (the device screen borders are schematized by the blue lines).
Unfortuantelly, the multiple bugs in the TextArea are making this UI hard to achieve.

To show these bugs, I made a small test case (NB: I didn't tried to set the exact style to match my  goal UI, this is just an example to show the bugs). 
Here is the code of this test form:

```
setTitle("Test");
setLayout(BoxLayout.y());
setScrollableY(false);
			
Container numdims_container = new Container(BoxLayout.x());
numdims_container.getAllStyles().setPadding(1, 1, 1, 1);
numdims_container.getAllStyles().setPaddingUnit(Style.UNIT_TYPE_DIPS);
Label length_lbl = new Label("L:");
length_lbl.getStyle().setMarginLeft(0);
length_lbl.getStyle().setMarginRight(0);
numdims_container.add(length_lbl);
TextArea pslength_tf = new TextArea(null,1,4,TextArea.NUMERIC);
//pslength_tf.getAllStyles().setMargin(0, 0, 0, 0);
pslength_tf.getAllStyles().setBorder(Border.createLineBorder(1, 0xFF000000));
pslength_tf.setMaxSize(4);
pslength_tf.setEditable(true);
numdims_container.add(pslength_tf);
Label width_lbl = new Label(" W:");
width_lbl.getStyle().setMarginLeft(0);
width_lbl.getStyle().setMarginRight(0);
numdims_container.add(width_lbl);
TextArea pswidth_tf = new TextArea(null,1,4,TextArea.NUMERIC);
pswidth_tf.getAllStyles().setMargin(0, 0, 0, 0);
pswidth_tf.getAllStyles().setBorder(Border.createLineBorder(1, 0xFF000000));
pswidth_tf.setMaxSize(4);
pswidth_tf.setEditable(true);
numdims_container.add(pswidth_tf);
Label height_lbl = new Label(" H:");
height_lbl.getStyle().setMarginLeft(0);
height_lbl.getStyle().setMarginRight(0);
numdims_container.add(height_lbl);
TextArea psheight_tf = new TextArea(null,1,4,TextArea.NUMERIC);
psheight_tf.getAllStyles().setMargin(0, 0, 0, 0);
psheight_tf.getAllStyles().setBorder(Border.createLineBorder(1, 0xFF000000));
psheight_tf.setMaxSize(4);
psheight_tf.setEditable(true);
numdims_container.add(psheight_tf);
numdims_container.add(new Label(" cm"));
		
//add(numdims_container);
add(BorderLayout.centerAbsolute(numdims_container));
```
and here is a video of the result obtained in the simulator:
https://streamable.com/h33vk

In the video, we can see multiple issues:

- when editing the text in a textarea, the text aligns vertically at the top of the textarea whereas it is is centered when the editing ends.
 
- each textarea has a limited size of 4 chars and 4 columns and 1 row. But the textarea width is a lot larger than these 4 columns (for example, in the first textarea, when entering the text "4444" we can see that there is still a lot of free space left after the latest character and the right border of the textarea. Actually, if the maxsize wasn't limited to 4 we would still have enaugh space to display 2 additional characters.) This shouldn't be the case and the max width of the textarea should be constrained by its maxsize (and its prefered width by its number of columns) + the left and right padding

- Even if each textarea has a limited size of 4 chars and 4 columns and 1 row, it is possible to put more characters in it by pressing "enter" after each group of 4 characters. So the number of rows=1 and maxsize=4 constraints are not working

- `TextArea` and `Label` each directly extend component and in my theme, derive their margins and padding (I used the default flat blue theme). Yet they have different default margins (default margins of 2 pixels for `Label` and of 13 pixels for `TextArea` and default padding of 13 pixels for both). This is a complete mess. Both should have the same default margins and padding and should derive from the theme default component style (which has 0 margin and padding if this default style is not explicitly defined in the theme)

**Comment by codenameone** [comment]
These aren't bugs. If you want the same size for the text areas you should use a grid/table layout.
When editing text the parent form (or some parent container) should have Y scrollability. 

- Vertical alignment might be broken due to scaling. You also set margins only for `getStyle()` which you shouldn't use in this case. If this is happening on the device with a properly set text area that might be interesting.

- Width is a hint for preferred size uses maximum char width e.g. `W` which is wider than `4`. We can't tell in advance what you will type into the area

- Those are hints for setting the preferred size of the text area not hard limits. See this for masking credit card input: https://www.codenameone.com/blog/validation-regex-masking.html
If you want one line you should use `TextField` not area.

- Each theme has its own margin/padding for components. I agree this is a bit messy but there's no way around it as components look differently on different OS's. E.g. on iOS a text field should be padded but on Android we must leave side padding 0 and have margin otherwise the underline border looks "weird".

**Comment by ramsestom** [comment]
- I don't understand how scaling would affect vertical alignment when editing and not when editing is done. Anyway I made a simpler test case with only the following Form code
```
setTitle("Test");
setScrollableY(false);
			
TextArea pslength_tf = new TextArea(null,1,4);
pslength_tf.getAllStyles().setBorder(Border.createLineBorder(1, 0xFF000000));
pslength_tf.setMaxSize(4);
pslength_tf.setEditable(true);
add(pslength_tf);
```
and, as you can see on the video: https://streamable.com/25wib the issue is still there.

- OK for the different chars width. makes sense (didn't thought there would be so much width difference between 'W' and '4'). Testing with 4 'W' in my textarea, I detected another bug though. As you can see in the previous video, when editing ends my 4 'W' chars are rendered on two lines whereas the prefered TextArea width should have been computed to rendered them in a single line (NB: I didn't canged the default static `widestChar` property of `TextArea` which is 'W' by default so it is not a configuration related issue, it is really a bug)

- `setMaxSize()` is supposed to be a hard limit. Else it doesn't make sense and is redundant with the
 `columns` property. So beeing able to input more than 4 chars in a TextArea with a setMaxSize() set to 4 is a bug to me

- each theme may have its own margin/padding for components but in my theme file I define them as derived for both `Label` and `TextArea` and when I look at the platform base theme object for iOS or Android they are also defined as `Derive`. So in that case, padding and margin should be the same whatever the platform. If I want a specific look and feel for an OS, it should be defined in this OS specific theme file (and not hidden somewhere in the code, as it seems to be the case, with the developpers left with a cross-platform framework that actually render differently on different platforms by default without any information on this). By default, the look and feel should be the same on each platform.
Anyway, having a different default margin for `Label` and `TextArea` doesn't make any sense. A non editable TextArea should render exactly as a `Label` by default (which isn't the case for now). 
As for the problem of padding and margin differences between Android and iOS to correctly render the border, it wouldn't happen if TextArea was a pure lightweighted component as it should.

**Comment by codenameone** [comment]
- Scaling of the simulator is tricky because we need to place the native widget in a location/size that doesn't necessarily match. You can test this by unchecking "scrollable" in the simulator menu.

- This isn't something we care so much about. It's a "ballpark" to calculate a preferred size value that "makes sense". Since so many things determine the size/sensibility of a text component this is behavior that's bound to change. You probably don't create fields to type in W's

- This isn't clear from the docs so I see the confusion here. Older platforms had a hard limit on the native text editing size that defaulted to 124 characters in some cases. To circumvent this we used max size that allowed us to request more initial space when launching the native text editing. This isn't a limit we enforce. I think the right solution is to just deprecate that whole API as it's no longer applicable to newer platforms

- They aren't in the code. Their in the iOS/Android theme files which you can see in github. However, we might change that. E.g. if we think we want to be more consistent as you suggested. So you need to be more explicit. When you derive from Label or TextField/Area you derive from the native theme and that's defined in the native platform. In the designer tool we have an option to simulate a native OS where you can see how the native OS impacts your theme. I'm not sure if there's a lot more we can do to improve this. TextArea is mostly lightweight, the native portion exist during editing. If you think you can implement editing in Java with the iOS/Android keyboard (and localization) I suggest you try and look at our old code that implemented some of that for J2ME. It's super complex and provides a horrible UX in comparison to the OS native experience.

**Comment by ramsestom** [comment]
- "scrollable" isn't checked in my simulator menu. I tried to check it to see the difference and it just seems to have the same effect as checking "zoom". With or without "scrollable", the bug remains anyway. I compiled for android and couldn't see this bug on android though (everything looks fine on the android device) so I don't know if this bug is limited to the simulator or would also happen on a J2ME desktop target

- I agree this isn't a big deal. Still this is a bug though and it means that the textarea isn't really computing it's prefered width as it should. So, depending on the exact origin of this bug, it might impact other textarea specific usages... We can't tell. 

- ok I understand. I agree you should deprecate this function then and clearly comment the reason for this function in its header comment.

- In the designer tool, I can't really see how the native OS impact my theme when it is as subtle as a 2 px margin (instead of 0) or even a 12 px padding (instead of 0) as this only appear on the displayed example components and not in the theme component' style edition popup. What you should do is to display the derived values for the selected native type in this popup. For example, if I have iOS7 selected as a native type and I click on TextArea in my theme file, in the "Edit" popup, when I select margins and check "Derive", I would like to see the derived values greyed out (instead of '0') so as, ideally, the UUID of the parent component and associated theme these values would derive from (actually, having access to the whole "derivation" hierarchy up to the first parent that do not "derive" its values for this parametter would be the best. A bit like what you have for css in browser components style inspectors.)
As for the 100% lightweighted TextArea, I didn't say it is something simple to implement (so I would not try to do it as I just don't have the time for that). I just said it should be the case for a framework that claims to be lightweighted. Some other lightweighted frameworks I use (Flutter, OpenFL, libgdx) succeeded into implementing lightweighted textareas (and every other input components)  without any noticeable difference with the OS native experience for the user. So it is not impossible (although I agree it is more complex to implement a lightweighted text input component that just a static or a touch responsive one) and allows to have a component that is consistent on all platforms and for which you can fully control the behavior and look and feel (for example, changing the carret color in a TextArea would be quite easy if this component was fully lightweighted rather than using native ones)
