### ISSUE TITLE
Installation Issue: Failure copying native libraries [errorCode=-113]

### ISSUE THREAD

**Issue by mornegalanos** [codenameone/CodenameOne#2917]
Good Day,

Recently we started noticing that our Applications (that used to install fine), are unable to install on most android devices.
After some investigation we discovered that the problem seems to be related to native libraries we use (these are used for printer integration) or at least how they are packaged in the final APK.

The following error can be seen when debugging the installation process:

> 2019-09-12 13:39:55.858 2058-2150/system_process W/NativeHelper: Failure copying native libraries [errorCode=-113]
> 2019-09-12 13:39:55.858 2058-2150/system_process E/PackageInstallerSession: Commit of session 1943415760 failed: Failed to extract native libraries, res=-113

The installation process was debugged using the Nexus 5X API 29 x86 Emulator (from Android Studio) with the following environment:
**Model**
Android SDK built for x86
**Serial**
EMULATOR29X1X12X0
**Version**
10

**More about our Environment:**
We use Netbeans as our IDE, on Windows Platforms, using the built-in CN1 Emulator and the Nexus 5X API 29 x86 Emulator (from Android Studio). Physical phones tested where a Samsung Galaxy S9+ and a Huawei P20 Lite.

**More about our Application:**
We have an AAR library (TPSLibrary.aar) containing .so native libraries in the jni/armabi folder     - Library will be attached
This AAR library is then included in our CN1 library (PrinterLibraryCN1.cn1lib) for Printing               - Library will be attached
Our PrinterLibrary is, inturn, included in our main Application (BankingMobile.apk)                           - Test Apk will be attached
_Attachments:_ [Android.zip](https://github.com/codenameone/CodenameOne/files/3605581/Android.zip)

Previously, this setup installed perfectly and ran on all devices we came across.
However, recently we have not been able to install our Application on most devices I could find (including a Samsung Galaxy S9+ and a Huawei P20 Lite), due to this presumed library issue.

Has something changed in Android itself causing incompatibility? Has something changed on CN1 side that might cause this? Are we packaging our project incorrectly?
I assume it has to do with _armabi_ now being _armabi-v7a_ or something similar.

Assistance regarding this matter will be greatly appreciated.

Kind Regards,

**Comment by shannah** [comment]
@mornegalanos Are you doing a debug or release build?  

I tried adding TPSLibrary.aar to a test project and building it.  I had to disable proguard because I didn't know the proguard keep rules for it.  But both the resulting release and debug builds worked ok for me.

[This post](https://stackoverflow.com/a/27945893) suggests that apks are zipaligned by default for release builds, which is why I'm curious if you were doing release or debug?

**Comment by mornegalanos** [comment]
Hi @shannah 

Thank you for your response. You are right, I recall having issues with Pro-guard to a few years ago when we initially added the TPSLibrary. We had to alter the build hints to accommodate for that. 

Here  are our _Build Hints_ for Android:

```
android.release=true
android.proguardKeep=-dontwarn za.co.kineto.**  -dontwarn com.telpo.** -dontwarn com.zkteco.** -keep class com.telpo.** -keep class com.zkteco.** -keep class com.common.sdk
android.xpermissions=<permission android\:name\="android.permission.BLUETOOTH_ADMIN"/><permission android\:name\="android.permission.BLUETOOTH"/><uses-permission android\:name\="android.permission.BLUETOOTH_ADMIN"/><uses-permission android\:name\="android.permission.BLUETOOTH"/><permission android\:name\="android.permission.READ_PHONE_STATE"/><uses-permission android\:name\="android.permission.READ_PHONE_STATE"/><uses-feature android\:name\="android.hardware.usb.host"/><permission android\:name\="android.permission.USB_PERMISSION"/><uses-permission android\:name\="android.permission.USB_PERMISSION"/><uses-permission android\:name\="android.permission.WAKE_LOCK"/><permission android\:name\="android.permission.WAKE_LOCK"/>
android.targetSDKVersion=26
android.playService.ads=false
android.debug=false
```
We do an Android Release build as far as I know.

I have also changed the Build Hint for targetSDKVersion to 26 as Shai suggested here:
[https://groups.google.com/forum/#!topic/codenameone-discussions/3VdCzAbtY8c](url)

However, the build that is returned seems still is unable to install. The Android Manifest in that build seems to target the correct versions:
```
android:minSdkVersion="15"
    android:versionCode="100"
    android:versionName="1.0"
    android:installLocation="0"
    package="za.co.kineto.banking.mobile"
    platformBuildVersionCode="27"
    platformBuildVersionName="8.1.0">

    <uses-sdk
        android:minSdkVersion="15"
        android:targetSdkVersion="26" />

```

My last option is to try a manual zipalign as you suggested. I will do that now so I can provide you with feedback and the result.

**Comment by shannah** [comment]
Does it fail to install on the Android emulator (Nexus 5X API 29 x86 Emulator (from Android Studio)) also?

**Comment by mornegalanos** [comment]
Yes, it does fail on that Emulator too. Here is a log extract from logcat:
```
2019-09-17 15:23:34.749 2074-2178/system_process W/NativeHelper: Failure copying native libraries [errorCode=-113]
2019-09-17 15:23:34.750 2074-2178/system_process E/PackageInstallerSession: Commit of session 1108007580 failed: Failed to extract native libraries, res=-113
2019-09-17 15:23:34.766 2074-2186/system_process I/ActivityTaskManager: START u0 {dat=file:///data/user_de/0/com.google.android.packageinstaller/no_backup/package284667485546597472.apk flg=0x2000000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallFailed (has extras)} from uid 10044
2019-09-17 15:23:34.700 5256-5277/com.google.android.packageinstaller I/chatty: uid=10044(com.google.android.packageinstaller) RenderThread identical 1 line
2019-09-17 15:23:34.710 5256-5277/com.google.android.packageinstaller D/EGL_emulation: eglMakeCurrent: 0xe07f5180: ver 2 0 (tinfo 0xc103c090)
```

**Comment by shannah** [comment]
I have reproduced the issue.  I have found that by adding a `splits` directive to the gradle build file, it fixes the issue:

https://stackoverflow.com/a/49473570

~~~~
splits {
    abi {
        enable true
        reset()
        include 'x86', 'armeabi-v7a', 'x86_64'
        universalApk true
    }
}
~~~~

I still need to read more on this directive before I decide how to deal with this problem in the general case.  I will either be setting adding a build hint to deal with this case, or instituting some auto-detection mechanism to automatically  add this to the gradle file.

**Comment by shannah** [comment]
Actually, I think that isn't the correct solution here.  It just hides the fact that your TPSLibrary.aar includes native code that is only compiled for armeabi.  When I do the split, it just removes it so that the platform doesn't try to load the library at all.  But in your case, you *want* it to be able to load the library.

The correct solution is for you to recomipile the TPSLibrary.aar to include all of the abis that you want to support.

**Comment by mornegalanos** [comment]
@shannah 

The TPSLibrary does have the following in it's build.gradle:
```
splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'mips', 'mips64', 'arm64-v8a'
            universalApk true
        }
    }

```

Also note that the native libraries are supplied by a 3rd party manufacturer (Manufacturer of Point-of-Sales systems, etc). The library and our own build has been unchanged for more than a year.

Is there no way to continue with these existing builds without rebuilding the whole stack?

**Comment by mornegalanos** [comment]
These libraries are used for specific devices (Telpo TPS). So on devices where they are not used, I don't mind if the don't extract or be used.
We just want the APK to install successfully on normal devices too, like it used to in the past

**Comment by shannah** [comment]
>  like it used to in the past

Nothing has changed on our end.  This is an issue with newer versions of Android that use ART instead of Dalvik.  

I experimented with adding a universal APK build hint so that it would build a universal APK.  However, what I found was that even universal APKs won't install.  Only the specific APK for the specified ABI would install.  E.g. If I do a split that generates separate APKs for each ABI, then I can install the one that is MyApp-x86_64-release.apk in the emulator fine.  However, I can't install the MyApp-universal-release.apk - which should work for all ABIs.  The reason is that the "splitting" identifies that the aar doesn't include support for the x86_64 ABI, so it strips it out altogether.  The universal APK leaves it in, I guess determining that each platform will know what to do with the native lib.  Unfortunately, this assumption is incorrect, and at runtime it just panics if it hits an aar that doesn't have support for its platform.

So, on a whim, I decided to play doctor on the TPSLibrary.aar file.  I noticed that in its root, it had an `armeabi` directory.  And it also had a `jni/armeabi` directory (which contained all of the .so files).  I figured that perhaps one of these is used as a litmus test by Android during installation to check for ABI support.  So I extracted the .aar, created `x86_64` and `jni/x86_64` empty directories, and rezipped the aar with its new contents.

Then I tried a build and was able to install it fine.

I suspect that if you build the TPSLibrary.aar with current android tools, it will add these directories automatically.  But the one you are using is problematic as it is.

Here is the console log showing the "doctoring" that I did:

~~~~
Steves-MacBook-Pro:tmp shannah$ ls
TPSLibrary.aar
Steves-MacBook-Pro:tmp shannah$ unzip TPSLibrary.aar 
Archive:  TPSLibrary.aar
  inflating: AndroidManifest.xml     
  inflating: R.txt                   
  inflating: classes.jar             
   creating: jni/
   creating: jni/armeabi/
  inflating: jni/armeabi/libcard_reader.so  
  inflating: jni/armeabi/libcollect.so  
  inflating: jni/armeabi/libdecode.so  
  inflating: jni/armeabi/libidcard.so  
  inflating: jni/armeabi/libled.so   
  inflating: jni/armeabi/libledpower.so  
  inflating: jni/armeabi/libmoneybox.so  
  inflating: jni/armeabi/libpicc.so  
  inflating: jni/armeabi/libposutil.so  
  inflating: jni/armeabi/libserial_port.so  
  inflating: jni/armeabi/libsystem_util.so  
  inflating: jni/armeabi/libtelpo_msr.so  
  inflating: jni/armeabi/libtelpo_printer.so  
  inflating: jni/armeabi/libtelpo_serial.so  
  inflating: jni/armeabi/libusb_util.so  
   creating: libs/
  inflating: libs/core-3.1.0.jar     
  inflating: libs/SmartCardLib.jar   
  inflating: libs/telpo_api.jar      
   creating: armeabi/
Steves-MacBook-Pro:tmp shannah$ ls
AndroidManifest.xml	armeabi			libs
R.txt			classes.jar
TPSLibrary.aar		jni
Steves-MacBook-Pro:tmp shannah$ ls -la
total 2216
drwxr-xr-x   9 shannah  staff      306 18 Sep 10:52 .
drwx------@ 11 shannah  staff      374 18 Sep 10:52 ..
-rw-r--r--@  1 shannah  staff      315  1 Feb  1980 AndroidManifest.xml
-rw-r--r--@  1 shannah  staff    77411  1 Feb  1980 R.txt
-rwxr-xr-x@  1 shannah  staff  1047446 11 Sep 19:29 TPSLibrary.aar
drwxr-xr-x@  2 shannah  staff       68  1 Feb  1980 armeabi
-rw-r--r--@  1 shannah  staff      680  1 Feb  1980 classes.jar
drwxr-xr-x@  3 shannah  staff      102  1 Feb  1980 jni
drwxr-xr-x@  5 shannah  staff      170  1 Feb  1980 libs
Steves-MacBook-Pro:tmp shannah$ ls armeabi/
Steves-MacBook-Pro:tmp shannah$ mkdir x86_64
Steves-MacBook-Pro:tmp shannah$ ls
AndroidManifest.xml	armeabi			libs
R.txt			classes.jar		x86_64
TPSLibrary.aar		jni
Steves-MacBook-Pro:tmp shannah$ mkdir jni/x86_64
Steves-MacBook-Pro:tmp shannah$ rm TPSLibrary.aar 
Steves-MacBook-Pro:tmp shannah$ zip TPSLibrary.aar *
  adding: AndroidManifest.xml (deflated 41%)
  adding: R.txt (deflated 82%)
  adding: armeabi/ (stored 0%)
  adding: classes.jar (deflated 10%)
  adding: jni/ (stored 0%)
  adding: libs/ (stored 0%)
  adding: x86_64/ (stored 0%)
Steves-MacBook-Pro:tmp shannah$ ls
AndroidManifest.xml	armeabi			libs
R.txt			classes.jar		x86_64
TPSLibrary.aar		jni
Steves-MacBook-Pro:tmp shannah$ jar tvf TPSLibrary.aar 
   315 Fri Feb 01 00:00:00 PST 1980 AndroidManifest.xml
 77411 Fri Feb 01 00:00:00 PST 1980 R.txt
     0 Fri Feb 01 00:00:00 PST 1980 armeabi/
   680 Fri Feb 01 00:00:00 PST 1980 classes.jar
     0 Wed Sep 18 10:53:09 PDT 2019 jni/
     0 Fri Feb 01 00:00:00 PST 1980 libs/
     0 Wed Sep 18 10:52:47 PDT 2019 x86_64/
~~~~

**Comment by shannah** [comment]
I see that I made an error with the rezipping of the .aar.  The .so files weren't included.  I'll need to test again.

**Comment by shannah** [comment]
Unfortunately when I zip the aar correctly, it fails to install again.

**Comment by shannah** [comment]
Experimented some more.  The problem is that for each .so file it finds, it seems to need to link *something* into the app.  Even in the emulator which has a preferred ABI of x86_64, it will try to use the .so file in the armeabi directory as a fallback, because, apparently that would work in some cases.  I'd have to look into it deeper to see exactly what configurations it will accept.  E.g. I read that the emulator can still use armeabi native libs - so it looks for x86_64 libs first, and then will fall back to a second choice. 

I was able to make the library work by making dummy .so libs for each abi correspoding to every .so file that you have inside the armeabi directory.  This way, the installer will always choose that dummy .so to link instead of the problematic one in the armeabi directory.

I wrote a php script that does this automatically.  Here is the resulting TPSLibrary after modifying it.


[TPSLibrary.aar.zip](https://github.com/codenameone/CodenameOne/files/3628354/TPSLibrary.aar.zip)

You can inspect it and see all the dummy .so files.

Building an APK with this library will install fine everywhere.

I posted the php script here.
https://github.com/shannah/aarfix

All it does is find all of the .so files, and makes a dummy version for each of the abis for which the .so doesn't already have a corresponding version.

The TPSLibrary I posted above will probably not work correctly on your devices that *actually* support the native libs you have in it.  This is because it has dummy .so files for armeabi-v7a and arm64-v8a, which will probably take precedent over armeabi in every case.   You need to figure out which devices your native libs will work on, and only generate dummy .so files for the *other* ABIs.

In the php script, this can be controlled by editing this constant:
https://github.com/shannah/aarfix/blob/master/aarfix.php#L18

~~~~
const TARGET_ABIS = array('armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64');
~~~~

Now, it might have been sufficient to simply rename the armeabi directory to something more specific, like armeabi-v7a (if the so file is 32 bit) or arm64-v8a (if the file is 64 bit), but I didn't try that.  There's a lot of experimentation that could be done to narrow down the problem.

The only other solutions to this issue that I could find, was to generate a split build where you generate a separate APK for each ABI.  But this more cumbersome - as with this library even the "universal" build doesn't install correctly.  

I think, in the end, we were probably just dealing with an old .aar that was compiled before 64 bit was a thing.  Correct me if I'm wrong.  I investigated this in probably more detail than I should have because I wanted to ensure that we didn't have an issue with supporting android 10.  I'm satisfied that we don't have an issue there.  It appears to just be that the native libraries need to be updated.

**Comment by mornegalanos** [comment]
Hi @shannah,

Thank you for all the feedback and support. You have really gone out your way to help us with this issue and we really appreciate it. 

I am going to take a look at all your suggestions in detail and see if we can come up with a solution to our problem. I have asked the supplier for their latest SDKs too. Maybe if they come back with newer libs, this issue can be resolved.

**Comment by mornegalanos** [comment]
Hi @shannah 

I received new libs from Telpo and rebuilt the .aar.
Everything seems to package correctly.

When I push the build through CN1, it builds successfully and if I unzip it, it looks correct (regarding layout).

Unfortunately, it still doesn't install.

I assume the same issue applies, even though all the native libs are now present. I was hoping it should work now with some "Universal build".

I will attach the latest .aar and our APK
[V2.zip](https://github.com/codenameone/CodenameOne/files/3631659/V2.zip)

**Comment by shannah** [comment]
Notice that their new TPSLibrary now includes libs for arm64-v8a and armeabi-v7a, but still includes the armeabi directory.  And doesn't include any x86 or x86_64.

So my guess is that this will install on any device you try - but might not in the emulator.  Fix this by adding dummy libs for x86 and x86_64.   It is also possible that simply removing the armeabi libs will fix this, since the emulator may be falling back to this, and failing.  Actual devices shouldn't need armeabi anyways as they'll find what they need in the more specific arm64-v8a or armeabi-v7a directories.

**Comment by mornegalanos** [comment]
Hi @shannah 

Thanks for the feedback. I ended up stripping out all the native libraries from Telpo TPS, and rebuilding new versions of our apps without it.

For now, I will leave it like that until I can figure out a way to include the TPS libs without breaking installs. At least the clients can now use the App again and print on non-Telpo devices.

Thanks!
