### ISSUE TITLE
Automatically add bottom screen padding/white space for the iPhone X task switch bar 

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#2946]
It is necessary to automatically add padding/white space at the bottom of a Form when used on iPhones/iPads which use the bottom navigation bar (devices without physical home buttons).  See attached image for example. 

Without this whitespace, several common iOS interactions like switch app or slide down to bring the top half of the screen down in reach for your thumb will also activate any CN1 UI components at the bottom of the screen, e.g. tabs at the bottom of the screen will be selected, pickers will be activated etc. making the user experience really annoying. 

I would consider this correction **Urgent** since it prevents creating apps for recent generations of Apple devices. 

First raised here: https://stackoverflow.com/questions/58680150/how-to-leave-white-space-for-the-iphone-x-task-switch-bar-at-the-bottom-of-the-s

![image](https://user-images.githubusercontent.com/16265939/68248186-9bba8d00-001c-11ea-9f1a-5a777c3451c5.png)

**Comment by ThomasH99** [comment]
Any news on this topics? It keeps annoying me on my own phone, so I'm thinking others may be interested in the fix as well.

**Comment by shannah** [comment]
I've implemented two new methods:

1. Form.getSafeArea(Rectangle) - Gets the "safe" area to render in the current form, which will provide bounds that won't be covered by things like "the notch" and the taskbar.
2. Container.setSafeArea(boolean) - Sets a container to always provide enough padding so that its children are rendered in the "safe" area.

You can see the sample of how to use the 2nd API here.  https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/SafeAreasSample/SafeAreasSample.java
