### ISSUE TITLE
RFE: androidX support 

### ISSUE THREAD

**Issue by schreiby** [codenameone/CodenameOne#2948]
Hi, 

Given that Google requires (as of 11/1/19) that all apps targetSdk 28 and support library 28 is the last before androidX, could you please build in support for androidX? Google is really advocating for migrating to it.

Thanks.

**Comment by shannah** [comment]
I've added a build hint `android.useAndroidX=true` that will cause the build to use AndroidX instead of support libraries.  Currently this will also run a find and replace all source files to replace old support classes and artifacts with their AndroidX equivalents.  This is a bit crude and can be turned off with the `android.migrateToAndroidX=false` build hint, but it should probably be kept on for now to ensure maximum compatibility with existing cn1libs and projects that might be still be using support libraries.

Even the CN1 core sources still use the support libraries right now as I'm not ready to go "all in" on AndroidX yet.  At some point in the future we can actually change those sources, and gradually phase out the need for the `android.migrateToAndroidX` build hint (which defaults to true right now).

Summary:  You just need to add `android.useAndroidX=true` and it will use android X.  This will force build tools version to 28.

Not sure if this will be included in this week's update.  Will be certainly in next week's update though.

**Comment by fhasni** [comment]
When this version with androidX compatibility could be available?

**Comment by codenameone** [comment]
This was already implemented as indicated by the comment from @shannah
