### ISSUE TITLE
missing method in "Preferences"

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2959]
The preferences implementation doesn't include a method for "keys()"

It appears this functionality would be very easy to provide, but it can't be
added by encapsulation because the underlying structures are private.

**Comment by codenameone** [comment]
This is intentional and also intentional for client properties. We use preferences/client properties to store internal state. This is state we can't guarantee as an API and so we don't want developers to rely on that. If keys were exposed developers would quickly rely on such data without reading the docs or checking the code/intention and their code will break.
