### ISSUE TITLE
Facebook login has stopped working on iPhone 6s

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3063]
Hi,

I haven't changed anything but in the course of last month this has stopped working specifically on my iPhone 6s. `doLogin()` doesn't trigger any callback anymore. First it stopped working on my debug builds, I thought maybe it's just there. Today I publish a fresh production build after about a month since my last one and this is now also happening in production. This is quite bad as I can't know which other users with what other devices are experiencing this and dropping the app because they can't sign in

This still works on iPad 4 (my only other iOS device)

**Comment by shannah** [comment]
What versions of iOS are running on your iPhone 6s and iPad 4?

**Comment by shannah** [comment]
I've reproduced it.  It seems that iOS 13 requires a newer version of the Facebook SDK than we're using.  (We're on 4.39.0), but iOS 13 needs 5.6.0.  Unfortunately 5.6.0 has some breaking changes so I need do a bit of work on our implementation to adapt to their changes. 

Hopefully I can have this working today so that it will be in the update on Friday.

**Comment by shannah** [comment]
I've fixed this in git.  It will be part of the next update on Friday.

**Comment by javieranton-zz** [comment]
Just seen this. A massive thank you!
