### ISSUE TITLE
SafeArea not working for a Form displaying an overflow menu or a Dialog

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3072]
From StackOverflow (https://stackoverflow.com/questions/61035405/safearea-not-working-for-a-form-displaying-an-overflow-menu-or-a-dialog , Shai asked to file an issue and remarked it is probably linked to use of Dialogs)

I've noticed on iPhone Xr with iOS 13.3.1 that the new support for SafeArea (https://www.codenameone.com/blog/safe-areas.html) is not working in (at least) a few situations.

When setSafeArea(true) is set for a Form it displays correctly within the safe area. But when the Form opens the Toolbar overflow menu or displays a Dialog, the Form is immediately expanded to fill the entire screen, just as if the safeArea was not activated. When the overflow menu or dialog closes, the Form is redisplayed correctly within the safe area. This gives a very jumpy/jittery experience.

I believe I've seen the same issue in other situations, so the problem may be more general than just these two situations.

**Comment by shannah** [comment]
@ThomasH99  Can you share a small test case?

**Comment by shannah** [comment]
I've reproduced an issue with the safe areas not being respected while rendering the form underneath a dialog.  I've updated the SafeAreasSample to include a button to open a dialog to test this out.  You can check out the latest sources and run against that to verify that it fixes your test case.

I'm closing this for now, as I think this was probably this issue.  Will reopen if you produce a test case that still isn't fixed by this change.

**Comment by ThomasH99** [comment]
Thanks for being so responsive Steve. The SafeArea was a really nice addition with big impact on usability :-) I'll check it asap (and report if I notice the issue in other circumstances).
