### ISSUE TITLE
With SafeArea active, overflow menu overlaps the 'open menu' icon, preventing clicking on it to close the menu

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3103]
I found this issue with SafeArea: when using the overflow menu, clicking it will position to menu too high up on the screen, overlapping some of the toolbar and in particular the 'open menu' icon so it cannot be clicked to close the menu.

**Comment by shannah** [comment]
I cannot reproduce.  Please modify [this test case](https://github.com/codenameone/CodenameOne/blob/47320a12743d7d2ff0a601b664e611d95f659b66/Samples/samples/SafeModeOverflowMenuTest3103/SafeModeOverflowMenuTest3103.java) to reproduce the problem.

**Comment by ThomasH99** [comment]
Thanks Steve, I finally got around to this. Your test sample didn't turn safeArea on so you wouldn't have seen the issue. 

I've update start() of your test to the code below which makes it easy to see the issue: select "Safe area ON" in the overflow menu and then reselect the overflow menu and you will see it overlaps with the 'three points' icon used to select the overflow menu. 

Btw, is there any way to activate the SafeArea in the Simulator? That can help test code without spending any of precious 100 monthly build points to test on the device. And it would make it easier to define the layout and css to account for safe area.  

````
    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Label status = new Label("Safe area OFF");
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.setSafeArea(false);
        hi.getToolbar().addCommandToOverflowMenu("Safe area ON", null, ev -> {
            hi.setSafeArea(true);
            status.setText("Safe ON");
            hi.revalidate();
            System.out.println("Item 1 selected");
        });
        hi.getToolbar().addCommandToOverflowMenu("Safe area OFF", null, ev -> {
            hi.setSafeArea(false);
            status.setText("Safe OFF");
            hi.revalidate();
            System.out.println("Item 2 selected");
        });
        hi.add(new Label("Hi World"));
        hi.add(status);
        hi.show();
    }
````

**Comment by ThomasH99** [comment]
Tried to assign the issue back to you, but I don't seem to have the rights. Hope you spot it anyway :-)

**Comment by shannah** [comment]
You shouldn't set the form itself to be a safe area.  The toolbar is already a safe area by default.

**Comment by ThomasH99** [comment]
Thanks Steve. I've used setting the Form to safeArea as an easy way to make every form respect the safe area (since basically I want your entire app to be 'Safe'). Is there another best practice for achieving this? E.g. should I systematically set the contentPane to Safe?

**Comment by shannah** [comment]
Setting the whole thing to be "safe" is problematic.  When a container is "safe" it will automatically add padding as necessary so none of its children overlap unsafe areas.  But you *do* want the toolbar to overlap the notch.  You just don't want its children to.  If you have tabs, you *do* want the tabs to bleed to the edge (and overlap unsafe areas), but you don't want their contents to overlap unsafe areas.

Certain components such as the toolbar and tab buttons are already configured to be safe areas.  Better to be more specific about which things should be safe.

You can also use setSafeAreaRoot, to specify that a container serves as the "root" for a safe area.    A safe area root is the starting point from where safe areas are calculated from.  By default Form is a root.  But in some cases, if you're pre-laying out a component before it transitions onscreen, you might want to set other things as roots so that  CN1 applies safe areas properly before the container is on screen.

**Comment by ThomasH99** [comment]
Thanks Steve! I didn't know that Toolbar and Tabs were automatically configured as safe (I thought  it was due to my setting the Form safe :-)). I realize the whole safe area is a bit more complex that one would think at first. If not already done, it would be great to add this info to the documentation. I also just read the comments on setSafeAreaRoot that I hadn't seen before - not so easy to understand, maybe an illustration in the doc would be useful. 

I will try systematically setting the ContentPane safe to start with, hopefully that will work in most cases.

**Comment by ThomasH99** [comment]
Sorry for not getting back to this sooner. This has fixed the problems I've seen, so closing the ticket. Again, thanks for you help Steven.
