### ISSUE TITLE
Making a ComponentGroup w RadioButtons lead components prevents selecting the Radio buttons

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3105]
An update to CN1 some time in the last few months broke part of my code. Suddenly I couldn't select the RadioButtons in a ComponentGroup anymore. 

I've finally identified the reason, it is due to adding the ComponentGroup as Lead component for its surrounding Container. I do this in a subroutine used for other user input fields like Buttons and Pickers. 

Now I've identified the problem I've fixed my code, but I guess it is not the intended behavior, so I wanted to report it. 

In the example code below, you can select the RadioButtons in the first group, but not the second where the ComponentGroup is made Lead of its Container. 

````
Form hi = new Form("Lead component breaks ComponentGroup", BoxLayout.y());

ButtonGroup group = new ButtonGroup();
ComponentGroup cgroup = new ComponentGroup();
Label editFieldLabel = new Label("");
Container visibleField = BorderLayout.centerCenterEastWest(cgroup, editFieldLabel, null);
RadioButton r1 = new RadioButton("R1");
group.add(r1);
cgroup.add(r1);
RadioButton r2 = new RadioButton("R2");
group.add(r2);
cgroup.add(r2);
hi.add(visibleField);

ButtonGroup group2 = new ButtonGroup();
ComponentGroup cgroup2 = new ComponentGroup();
Label editFieldLabel2 = new Label("EDIT2");
Container visibleField2 = BorderLayout.centerCenterEastWest(cgroup2, editFieldLabel2, null);
RadioButton r3 = new RadioButton("R3");
group2.add(r3);
cgroup2.add(r3);
RadioButton r4 = new RadioButton("R4");
group2.add(r4);
cgroup2.add(r4);
hi.add(visibleField2);

//What causes the problem: 
visibleField2.setLeadComponent(cgroup2); //making the ComponentGroup lead makes it impossible to select the radio buttons

hi.show();

**Comment by shannah** [comment]
When a container has a lead component set, it will hog all of the events inside its bounds - preventing children from receiving the events.  All events are "captured" by the container, but are piped to other lead component of the container.
If you want children of the container to still "work", you need to set their "blockLead" flag so that they will capture events.  I.e. call `cgroup2.setBlockLead(true)`.

That said, there was a bug that caused the cgroup2 to grab events that should have gone to its children (the radio buttons).  This is fixed now and will be part of the next update.  I've added a test case in the SamplesRunner project named RadioButtonLeadComponentTest3105 that you can run right now to verify that this works - you'd need to run from sources (check out git).
