### ISSUE TITLE
"JavaFX Is Loaded" is still printed when running with the CEF port

### ISSUE THREAD

**Issue by shai-almog** [codenameone/CodenameOne#3245]

**Comment by shannah** [comment]
Was this in the Simulator, Codename One Settings, the GUIBuilder , or something else?

**Comment by shai-almog** [comment]
Simulator. It's from a comment here: https://www.codenameone.com/blog/big-changes-jcef.html

**Comment by shannah** [comment]
Ah.  I see.

> I have installed cef as instructed above. However, when I run my app in simulator I still see 
CSS> JavaFX is loaded
in the console output. Is this expected? I mean, do you still use JavaFX in simulator even if cef is installed?

It is the CSS compiler which still uses JavaFX.    This is going to be a little bit more work because the CSS compiler uses the JavaFX webview to generate borders that can't be achieved natively in CN1.   Porting this to CEF will require some work.

**Comment by shannah** [comment]
CSS compiler no longer uses JavaFX.
