### ISSUE TITLE
Two open source tools for Codename One developer’s community. Need help for the Mac OS and Linux versions

### ISSUE THREAD

**Issue by ericlight** [codenameone/CodenameOne#3296]
Hi all,

I have built recently two desktop tools that I want to give for free with the source code on GitHub. These tools are codenameOne Linguist and CodenameOne Extensions. Their source code are portable and totally cross platform (written in C++/Qt with a little Go for some parts). 

I ‘am a windows user so for the first launch, I can only give a windows binary. If you are a Mac OS or Linux user, you can help to build the source code for your platform and for others developers of the community. I prepare some instructions for you to help in that way and you will find them on the GitHub soon. 

Everything is ready but before I put them online, I have to make some final tests and record two video tutorials about these apps. All of these will be available on GitHub maybe in two weeks or less. Before the launch, I will add a third tool to manage the two previous tools easily for those of you who want to have all in one place.

_PS: I made this post here on GitHub because we don’t have a real internal forum on the Codename One website. Stack Overflow is just for questions and the Google Groups is a crap and is not fun to use. It’s also too old. There are many open source forum CMS out there so can you pick one and install it on your server please? It will be very helpful. The community must have their own private forum with different sections or sub-forum to share all they want. Thanks!_

Here are CURRENT features below:

**CODENAME ONE LINGUIST** (DESKTOP SOFTWARE + CN1LIB)

- You can scan all your project's Java source code files and extract words that you want to translate. All in one click
- You can choose between 186 languages to translate your app. These languages are also available in the CN1LIB that comes with the software
- You can add translated words directly in your project resource file (theme.res)
- You can also add translation keywords manually
- You can export translated contents to CSV, JSON and Java properties formats
- You can import translated contents from CSV, JSON and Java properties formats
- You can sort keys and values by ascending and descending order
- You can add and override predefined words/contents from Codename One UI components
- You can duplicate your key to the value field
- There is an auto-saving feature after value modification and validation
- There are others features on the roadmap. I will publish the roadmap too.

**CODENAME ONE EXTENSIONS** (DESKTOP SOFTWARE)

- You can explore all libraries
- You can search a library using its name, tag or author name
- You can download library
- You can add/install a library in any Codename One project. The refresh libs part is done automatically if you have ANT in your environment path
- You can remove/uninstall a library from a project. It will not only remove the library itself and his files in the "lib/impl" directory. It will also remove the build hints added by the library that you remove. The refresh libs part is done automatically if you have ANT in your environment path
- You can get a view of all your projects that use a CN1LIB
- You can get all libraries that are used in a selected project so you can uninstall the library you want.
- There are others features on the roadmap. I will publish the roadmap too.

Now, here are some screenshots

![CN1Ext1](https://user-images.githubusercontent.com/9592818/97808202-81ca7f00-1c5d-11eb-8248-fb260ecf301f.png)

![CN1Ext2](https://user-images.githubusercontent.com/9592818/97808210-8a22ba00-1c5d-11eb-9b41-4041bed6717d.png)

![CN1Ext3](https://user-images.githubusercontent.com/9592818/97808217-8f800480-1c5d-11eb-99ce-000659d4bd68.png)

![CN1Ling1](https://user-images.githubusercontent.com/9592818/97808221-9575e580-1c5d-11eb-8f70-3fb1c044fd0d.png)

![CN1Ling2](https://user-images.githubusercontent.com/9592818/97808225-9b6bc680-1c5d-11eb-8c01-12554006158f.png)

![CN1Ling3](https://user-images.githubusercontent.com/9592818/97808230-a161a780-1c5d-11eb-81e5-eed0bd017ab9.png)

![CN1Ling4](https://user-images.githubusercontent.com/9592818/97808236-a6bef200-1c5d-11eb-9448-f9d7f1ffd22c.png)

![CN1Ling5](https://user-images.githubusercontent.com/9592818/97808240-ab83a600-1c5d-11eb-95a5-f40bd4e31b3f.png)

Can i have your opinion about these tools ? Thanks! Cc @jsfan3 @shannah @shai-almog

**Comment by jsfan3** [comment]
I thank you for expressly asking for my opinion too, but I don't know how much it could be worth. I don't work for Codename One, I'm just a user.

About your two software, I have some doubts.

I understand your enthusiasm and your desire to share, which is certainly commendable. However, it would make more sense to me that these kind of improvements should be integrated directly into the Codename One plugin, in order not to have a duplicate of already existing functions and not to introduce bugs for which it would not be immediate to understand if they should be searched in your software or in Codename One's software. I don't know if "Codename One Preferences" and "Codename One Designer" are open to external contributions.
 
The automatic uninstallation of cn1libs seems to me very risky: consider that there are cases where the installation of one or more cn1libs requires a manual revision of the build hints, so a fully automated cn1libs removal can have unexpected effects.

As for translations, I don't use the theme.res, but external JSONs files, with Java code to support their use inside my apps. So I understand the need to have something different and more advanced than the "Localization" tool of the Codename One Designer, or rather, just something external to the Codename One Designer. In my first experiments with Codename One, I also created a software to automatically translate the user interface into another language, through the automated use of Google Translate: then, however, I abandoned this path, because machine translations into languages I don't know are risky.

That said, I understand the need to improve the existing tools, so I appreciate your work. However, I keep asking myself if the improvements can be integrated into the official Codename One software, but it is not up to me to answer, nor do I know if this is what you want.

**Comment by ericlight** [comment]
Hello @jsfan3

Don't worry, i know you are not a Codename One employee and i ask for your thoughts just to know what you think about that. I use Codename One since 2012 and i was a previous user of LWUIT too. I'am also the author of the first book about this framework so i know very well this framework. I built these tools first for my needs but i dont want to keep them just for myself. This is why i want to give them to the community. Anyway, I understand all you said. I don't know what Shai will think about all this but i have many others things i want to build like a complete, modern and great theme builder for Codename. Since 2012, Codename One tools are still the same and old so if my contributions can be integrated in Codename One by Shai, il will be great because people need these tools and i plan to continue to improve them and to create others tools. if not, others developers can use it even if Shai doesn't accept to include them. It will be open source and well maintained so it will help somebody. Thanks Francesco for your thoughts.

**Comment by ericlight** [comment]
About your opinion about automatic uninstallation of cn1libs, it's something which is requested many times by the user. Even you @jsfan3 asked for that with a Github RFE that i found so I don't understand why you think now it's a risk to do that. Some libraries add build hints to the project so it's logic to remove them too if these libraries are removed to the project in my opinion.

Sorry for my english if you find some issues. It's not my primary language :)

**Comment by jsfan3** [comment]
Don't worry, I have difficulty with English too. I think that at this stage a discussion on the automatic removal of cn1lib would take us off track, as it is just a detail of the projects you are developing. Anyway I answer you on this point: I remember that I asked for this RFE, but afterwards I had a second thought. Let me give you a concrete example. Look at the `codenameone_library_appended.properties` and `codenameone_library_required.properties` files of CameraKit cn1lib (https://github.com/codenameone/CameraKitCodenameOne): there are some problematic build hints to handle automatically when removing this cn1lib. Specifically: `android.multidex` may be required by native interfaces developed independently (not linked to this cn1lib and added later), `android.buildToolsVersion` changes the compatibility level and we don't know if a change can affect the rest of the app (we don't know if it's required by native code inserted by the developer and not linked to this cn1lib), finally also `android.xpermissions` may be required by native code not linked to this cn1lib or others, but written directly by the developer. For my side, I keep track of all the hint builds I touch manually or that have been added automatically, I write the reason for their insertion or modification, so that I'm always aware of what I'm doing: what I do requires a lot of discipline, but it's the only way not to mess up when in a single app I have dozens of build hints, some cn1lib installed and many native interfaces written by me. I hope I've been able to make you understand the reasons for my perplexity on this point.

**Comment by ericlight** [comment]
Hello Francesco,
Thanks for your feedback, i appreciate. I read your reply and I understand now what you say. You are right and this issue can be resolve in different ways.

- I can disable/remove the build hints deletion from my tool so the user will remove them manually if he wants. The tool will just remove the library and it's files.

- I can also expose the list of build hints added by the library that the user wants to uninstall so he can choose only the build hints that he wants to remove or keep during the uninstall process.

I think i did it well to tag you on this discussion because it's an important thing that you expose :) Thanks !

Last question for you @jsfan3 . I know you use Linux so I want to know if you will be able to build the linux version of these apps one the source code is available ? Just to know if you can help in this way. Thanks !

Just another note that has nothing to do with the previous subject. I think if we (Codename One developers) want to wait the CN1 Team to build all these things one day, it will take many years and we will wait longer l'île now. CN1 is big and the team is very small so we have to contribute in others ways too and not only with CN1LIBS. 

The first time that Shai wrote in a post that they will split CN1 Designer features in small seperate tools, it's in 2016 (4 years ago) in this post: 
https://www.codenameone.com/blog/using-designer-command-line-options.html

I really liked this post because the RES format is opaque and the command line usage was the first step to help others developers to build tools for Codename One. For proof, I use this feature in the Linguist tool to call the designer silently to regenerate the "theme.res" with the translated contents inside. 

CN1 deserves more visibility ans better tools since that Time. 8 years (since 2012) is already too long i think to continue to wait so I will do my part to contribute not only with librairies but with good ,simple, intuitive and complete tools. If Shai accepts these tools, it will be great. If not, it will be an independant tools and i will continue to improve them.

**Comment by jsfan3** [comment]
Thank you for your contributions, we await the opinions of Shai and Steve. To answer your question, yes, I can help you compile on GNU/Linux and MacOS, but with one difference: I've been using GNU/Linux since 2000 and I know it well enough, while only two months ago I put my hands on a MacBook to write native interfaces with Xcode and so it's an operating system I know very little about.

**Comment by ericlight** [comment]
Thank you too Francesco for your opinions and to be able to help for the build for Linux and MacOS too. Waiting now for Shai and Steve opinions. 

Regards

**Comment by shai-almog** [comment]
FYI we'll migrate to a different forum once the new website is up.

As a Java tool I don't see why you wrote this in QT of all things. Right now we're pretty swamped with work. QT and C++ are a nightmare I personally don't want to get into. There are better/simpler solutions that can be done using existing tools e.g. a simple localization wizard integrated directly into the simulator. This would work for all platforms and can be seen instantly in the app. Adding support for standard properties files should be trivial and provide support for many 3rd party tools/services for localization.

Other than the remove feature (which is problematic) I don't understand the logic of replicating what Codename One Settings already does. If a library defines something required by a different library your approach to uninstall would break that. The "right way" to do that would require a change to the way libraries are installed so they no longer change codenameone_settings.properties and only integrate when the build is sent. Once we do that we'll add an uninstall feature.

**Comment by ericlight** [comment]
Hi ,
Ok for the forum. For Your Information, C++ and Qt are not a nightmare. Maybe for you but it's not. If I choose to build that tools in Qt, it's because i know it very well. CN1 is not really ready for desktop app and i don't know how to use Swing or  othersJava GUI toolkit. I use Qt since 2008 and it's one of the best framework for desktop app even if you don't like it.

Even if you can build desktop app with Codename One, it's not the right tool for that. CN1 is good for mobile app and miss many things for desktop. I can only use what I know the best and this is why I choose Qt. You don't like it and it's fine but i can't choose what i don't know to use. 

You asked me why i replicate CN1 Settings. I didn't replicate CN1 Settings. I build better extensions tools that what we have in CN1 Settings. 

The global impressions of your message is not positive so I understand your position. I will launch these tools, build others and will continue to maintain and to add features to them as an independant open source tools and contributions. I know it will help many developers so there is no problem with that. 

For those who what to wait the team to integrate all these features one day, they can. For those who want to waste more time, they will use my tools and contribute to the source code if they want. 

Thanks

**Comment by javieranton-zz** [comment]
Very interesting. I would love to see more integration with Qt too. But on the other hand, using Java in desktop CN1 apps totally makes sense as a lot of it can be reused and Java (for the most part) runs fine on desktops

Thank you so much for sharing this

**Comment by ericlight** [comment]
Thank you too @javieranton-zz  for your feedback,

I know it makes sense to use Java in desktop CN1 apps but i don't know Swing or SWT or AWT and CN1 is far to have all components to build modern and complete desktop tool because it miss many things. 

For mobile, CN1 is good than Qt but for desktop, it's not. I can only use what I know and this is why i use Qt. 

I promise to give to the community the best CN1 tools for free and my tools will always provide more possibilities and features than what CN1 will offer because i will dedicate myself to that. Just wait for the theme builder tool that i have in mind. It will be based on the CSS part of CN1. 

Regards

**Comment by ericlight** [comment]
Hi all,
As promised, my tools (3 tools) are now available on GitHub. You will find the features, roadmap, requirements, download links (releases and source code) and contributions informations on the following pages :

- CN1 Linguist - https://ericlight.github.io/CN1Linguist

- CN1 Extensions - https://ericlight.github.io/CN1Extensions

- CN1 Toolbox - https://ericlight.github.io/CN1Toolbox

In 24 hours, i will submit two videos tutorials to show you how to use CN1 Linguist and CN1 Extensions tools. 

I'am open for any suggestions. Thanks

Cc @shai-almog @jsfan3 @javieranton-zz
