### ISSUE TITLE
Maven doesn't support hotreload

### ISSUE THREAD

**Issue by shai-almog** [codenameone/CodenameOne#3402]
Open Maven project in intellij and debug on simulator.

Select the `Run` -> `Debugging Actions` -> `Reload Changed Classes` menu option from Intellij.

You get the following printout:
> Hotswap Agent not detected. To enable enhanced live class reloading feature, run with DCEVM JDK and add -XX:HotswapAgent=core to the VM options

**Comment by shannah** [comment]
I added that message.  I was having difficulty getting IntelliJ's hot reload to work with Maven, and frankly the hot-reload isn't very good anyways (it's only good for changing small bits of code - doesn't support adding new methods and classes, etc..),
so I did a bit of research on alternatives and found that [HotswapAgent](https://github.com/HotswapProjects/HotswapAgent) works great, so I added hot reload (based on HotswapAgent) support directly into the simulator.  The simulator now watches the source directories for changes and will trigger a full maven re-compile when changes are detected.  The Hotswap agent pulls in the changes seamlessly.  This works even if you add/remove classes and methods.  I sometimes need to do a fresh restart of the simulator, but for the most part this works well.

So far I have been testing with just using the [DEVM JDK11](https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases), which includes the hotswap agent, and just adding the -XX:HotswapAgent=core to the VM options in the IntelliJ settings, I'm going to explore making it more seamless so that users don't need to use any particular VM.

This is still experimental, but very promising.

Links:

1. [Hotswap Agent](https://github.com/HotswapProjects/HotswapAgent)
2. [DEVM JDK 11 with Hotswap Agent](https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/releases)
3. [Hotswap Agent IntelliJ plugin](https://github.com/dmitry-zhuravlev/hotswap-agent-intellij-plugin) - I have not tried this, but I will be looking into its source as a reference.

I have been using this setup for the development of the Twitter UI kit and it has been *wonderful*.  I can make changes throughout the codebase and instantly (~5 second delay) see the results in my UI, without having to restart the simulator.

**Comment by shannah** [comment]
Maven supports Hot Reload via standard IDE debug mechanism - and it supports "Hot Restart" which is arguably more useful.
