### ISSUE TITLE
Maven projects from start should be cleaner and have gitignore by default

### ISSUE THREAD

**Issue by shai-almog** [codenameone/CodenameOne#3418]
The template should include a reasonably configured gitignore file excluding target, jars, classes etc.

Currently the template contains a lot of files on root such as netbeans files, eclipse launch files etc. It would be great if we can move all of that stuff into a directory so the project won't look so "scary".

**Comment by shannah** [comment]
Most of the cruft is the late addition of the eclipse launch files (17 files).  These seem to require an "extra" import step on the newest Eclipse so it might not be a loss to move these into a subdirectory.

The netbeans files (5 of them) need to be in the root (I think).
The .sh and .bat scripts (6 of them) could probably be moved into a "bin" directory.  These would need to be moved carefully because they are used in some of our tools (e.g. codename one settings).

**Comment by shai-almog** [comment]
Can we maybe move all of these out and in the readme say "if you use NetBeans copy these files to the root?"

**Comment by shannah** [comment]
Yes. I can do that.

Another thought I have is that we can try to make "common" more prominent by moving all of the "native" modules into a submodule called "native".  And rename "common" to "app". So the root directory would be:

pom.xml
app (used to be common)
native
     +--- javase
     +--- javascript
     +--- ios
     +--- android
     +--- win
tools. (A directory for IDE-specific files).
bin (a directory for all the shell scripts)
README.adoc

This will be a change that is bigger and may trigger some regressions because a lot of the stuff depends on the current structure.

**Comment by shai-almog** [comment]
That would be great. I'd leave the name common though. It's good. But if all the other stuff is under native it would be great!

**Comment by jsfan3** [comment]
Please consider the compatibility of any changes with projects using the current structure.
