### ISSUE TITLE
How to delete Splash screen in ios side?

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3538]
Every time that I open my app in ios side. I show other screen with the icon launcher of my app in the center and next it show my app.
There is a way to avoid this screen in ios side?

@shannah  this build hint is to avoid Splash screen in ios?

codename1.arg.ios.generateSplashScreens=false

**Comment by shannah** [comment]
The launch screen is unavoidable.  However, you can customize the launch screen by providing one or more of the following files in your project’s native/ios directory

Launch.Foreground.png – Will be shown instead of your app’s icon in the center of the screen.

Launch.Background.png – Will fill the background of the screen.

LaunchScreen.storyboard – A custom storyboard developed in Xcode, that will be used instead of the default storyboard.

**Comment by DurankGts** [comment]
it's possible to use my Form in cn1 side instead of a png?

**Comment by shannah** [comment]
No.  This launch screen is shown while the app is loading.  Your form won't be available yet.  As soon as the app is loaded, it displays your form.

**Comment by DurankGts** [comment]
I put this files Launch.Background.png ,Launch.Foreground.png in the native/ios directory and I set

codename1.arg.ios.multitasking=true

but is not working..

it's necessary add this file LaunchScreen.storyboard 

The launch screen is unavoidable. However, you can customize the launch screen by providing one or more of the following files in your project’s native/ios directory

Launch.Foreground.png – Will be shown instead of your app’s icon in the center of the screen.

Launch.Background.png – Will fill the background of the screen.

LaunchScreen.storyboard – A custom storyboard developed in Xcode, that will be used instead of the default storyboard.

**Comment by DurankGts** [comment]
any solution to this?

**Comment by DurankGts** [comment]
how can I avoid the first form the app icon?
