### ISSUE TITLE
GUIBuilder 7.02: selecting ActionEvent in Property Inspectors Events does not set internal dirty flag

### ISSUE THREAD

**Issue by weissms68** [codenameone/CodenameOne#3592]
There is no indication the *.gui files was changed and needs to be saved.

Steps to reproduce:

1. create GuiBuilder form: mvn cn1:create-gui-form -DclassName=com.example.MyForm
2. open GuiBuilder: mvn cn1:guibuilder -DclassName=com.example.MyForm
3. put Core Components Button into the form
4. in Properties Inspector switch to Event
5. click Action Event -> small x appears to the right -> no visual indication a save is needed
6. exit GuiBuilder
7. check contents of MyForm.gui file: cat common/src/main/guibuilder/com/example/MyForm.gui -> actionEvent="true" is missing from component "Button"

Open GuiBuilder again start from 5. but this time save before exit. Check the contents of MyForm.gui again -> actionEvent="true" is there.

If in contrast to the above the Text property of the Button is changed there is a visual indication that a save is needed.

**Comment by shannah** [comment]
I have committed some changes that will take effect in the next version (available next Friday).  These changes will disable the "Events" tab entirely in the GUI builder.  You can attache event handlers on your own your generated class' java code.

This is a temporary measure because the event handler generation code depended on the Codename One plugin, which is now deprecated.  I have filed a new issue that you can follow for re-implementing this feature in Maven.

https://github.com/codenameone/CodenameOne/issues/3594
