### ISSUE TITLE
GuiBuilder 7.02: Action Event is lost after other changes

### ISSUE THREAD

**Issue by weissms68** [codenameone/CodenameOne#3593]
Related to [issue3592](https://github.com/codenameone/CodenameOne/issues/3592) at least when it comes to setup for the reproducing steps.

1. ensure you have a *.gui file with a Button component having actionEvent="true"
2. start GUIBuilder
3. switch to Buttons Properties Inspector Events -> there is no "x" to delete the Action Event
4. change the Buttons Text property
5. save and exit GuiBuilder
6. check the *.gui file -> actionEvent is gone

Actually the bug is already visible in 3., though, this may go unrecognized for most users.

**Comment by shannah** [comment]
I have committed some changes that will take effect in the next version (available next Friday).  These changes will disable the "Events" tab entirely in the GUI builder.  You can attache event handlers on your own your generated class' java code.

This is a temporary measure because the event handler generation code depended on the Codename One plugin, which is now deprecated.  I have filed a new issue that you can follow for re-implementing this feature in Maven.

https://github.com/codenameone/CodenameOne/issues/3594
