### ISSUE TITLE
Facebook Android API has to be updated 

### ISSUE THREAD

**Issue by hajdarevicedin** [codenameone/CodenameOne#3725]
I am told on CN1 chat to report issue I have when building android on servers, and I am told the issue is similar to https://github.com/codenameone/CodenameOne/issues/3561 this one

Logs while building are attached
[error (2).txt](https://github.com/codenameone/CodenameOne/files/12358427/error.2.txt)

**Comment by shai-almog** [comment]
Our current version of the Facebook API is 8.2.0. We need to update probably to 16.*

**Comment by hajdarevicedin** [comment]
> Our current version of the Facebook API is 8.2.0. We need to update probably to 16.*

Any estimated time regarding this?

**Comment by shai-almog** [comment]
This will take a while. August is when most of us are on vacation and we have many open P1 issues still due to the terrible Android 13 migration. I doubt this will be an easy fix since Facebook tends to make everything hard.

**Comment by Eric-Chomba** [comment]
> I am told on CN1 chat to report issue I have when building android on servers, and I am told the issue is similar to #3561 this one
> 
> Logs while building are attached [error (2).txt](https://github.com/codenameone/CodenameOne/files/12358427/error.2.txt)

> I am told on CN1 chat to report issue I have when building android on servers, and I am told the issue is similar to #3561 this one
> 
> Logs while building are attached [error (2).txt](https://github.com/codenameone/CodenameOne/files/12358427/error.2.txt)

This is in your error log

_sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested targetsun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target_

Means there is a problem when reading JDK certificate which is probably causing Facebook SDK download failure.

I experienced similar problem some time back when trying to run/build ant project in simulator on windows 10 using Java 8 & Apache Netbeans 12.1

I tried to uninstall, clear caches & reinstall Java 8 and Netbeans but didn't work either .

I resolved this by installing Java 11 instead of Java 8.

Surprising I also uses Java 8 & same Netbeans version on Linux (Ubuntu) and both ant & maven projects builds seamlessly without  this JDK certificate problem.

**Comment by shai-almog** [comment]
@Eric-Chomba this is because the jar from facebook is no longer available and the link is no longer on maven central

**Comment by shannah** [comment]
I laid some groundwork for the facebook SDK update to the latest (16.2.0), this morning.  It requires a few changes that may have ripple effects.  ETA 2 weeks to get this rolled out for testing on the build server.

**Comment by Eric-Chomba** [comment]
In [this app](https://play.google.com/store/apps/details?id=com.zomuhtech.cn.features) Sign In menu, sign in with facebook is implemented using facebook sdk version 12.0.0

As shown in [this line](https://github.com/Eric-Chomba/FeaturesCN1-Maven/blob/425b2d883068e0952e0b0f21265a05c94d016ad5/common/codenameone_settings.properties#L5C3-L5C3), perhaps you can override the default facebook sdk version using this build hint

`codename1.arg.android.gradleDep=implementation 'com.facebook.android\:facebook-android-sdk\:12.0.0'; `

**Comment by pinktriangle** [comment]
Hi. Any further ETA on this as still causing build failures. TIA.

**Comment by shannah** [comment]
Default version of facebook sdk is now 16.0.0.  This will be used automatically if you send a build that requires facebook integration.
