### ISSUE TITLE
android sources no longer work

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#3759]
.. at least for virgin users.  The grade wrapper properties if produces look like this

#Wed Apr 10 15:27:10 PDT 2013
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=http\://services.gradle.org/distributions/gradle-1.12-all.zip

auto download of gradle fails.   It works if you change http: to https:

also note; gradle-1.12 seems like an odd requirement.

**Comment by shannah** [comment]
Fixed in https://github.com/codenameone/CodenameOne/commit/465966fcec766dd86d1499a51ef7b9dc806b78b4
and 
https://github.com/codenameone/CodenameOne/commit/7ac817119ea7f00403cd1119ea18a2232a43bafd

If using the android.useGradle8=true build hint, you also need to provide a `JAVA17_HOME` environment variable to point at a Java 17 JDK.
